### ISSUE TITLE
OMG ... I delete it ...

### ISSUE THREAD

**Issue by bibi21000** [OpenZWave/python-openzwave#1]
Hi guys
I'm an idot .. I try reactive the  docker webhooks with a fork on my personal github and delete the main one.
Sorry for that ...
No code is lost but all issues ...
I really apologize for that

**Comment by bibi21000** [comment]
The ownerwhip transfer to the openzwave team is on the road.
Please do not update your repositories until it is done

**Comment by bibi21000** [comment]
The transfer of owner ship is done.
Feel free to reopen your issues
Really sorry for that

**Comment by bibi21000** [comment]
All tags are also lost.
A new tag 0.3.0-b4 is on the road
Done

**Comment by izdi** [comment]
Well, that happens :D
BTW, is the latest tag stable ?

**Comment by bibi21000** [comment]
I try to re-activate the docker build ... but Docker can only synchronise with my personal github (not with the openzwave one).
So I fork it ...
But when I do commit, they came to my personal fork ... and I can't close issues directly in the commit, which is really helpfull
So I decided to remove my personal fork ... which delete the openzwave team one ...
...
:(

**Comment by bibi21000** [comment]
Don't know if it's because this repo was originally on my personal github and transfer to openzwave after ...
If you want to use the pyozwman, prefer the master branch, but yes the latest tag should come without bug (hummm without known bug) ...
Maybe if you use regional characters in your device name, there should be a problem.
Let me know
