### ISSUE TITLE
Python3 branch is not compiling

### ISSUE THREAD

**Issue by stefan-jonasson** [OpenZWave/python-openzwave#10]
I get these errors when compiling: 

```
src-lib/libopenzwave/libopenzwave.cpp:922:87: error: ‘ValueType’ is not an enumerator-name
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueType(enum OpenZWave::ValueType value);
                                                                                       ^
src-lib/libopenzwave/libopenzwave.cpp:922:98: error: ‘ValueType’ in namespace ‘OpenZWave’ does not name a type
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueType(enum OpenZWave::ValueType value);
                                                                                                  ^
src-lib/libopenzwave/libopenzwave.cpp:934:88: error: ‘ValueGenre’ is not an enumerator-name
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueGenre(enum OpenZWave::ValueGenre value);
                                                                                        ^
src-lib/libopenzwave/libopenzwave.cpp:934:99: error: ‘ValueGenre’ in namespace ‘OpenZWave’ does not name a type
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__OpenZWave_3a__3a_ValueGenre(enum OpenZWave::ValueGenre value);
```

**Comment by bibi21000** [comment]
Try to use INSTALL_ARCH method.
Look at https://github.com/OpenZWave/python-openzwave/issues/9

**Comment by stefan-jonasson** [comment]
I would love to use that method, but it seems like there is no pre-packaged python3 versions. 

We are using the lib for this project, https://github.com/balloob/home-assistant and right now it's not possible to install because nobody knows what version of the python3 branch actually did work. 

@bibi21000 do you have any plans releasing this as a pip PyPI package? That would really help with dependency management and simplify a lot for end users (if it's possible with the ozw bindings)!

**Comment by instantchow** [comment]
I'm also in the same boat as Stefan, wanting to use this with
home-assistant. For what it's worth. I was able to get as far as building
the pre cythoned package from the bibi21000.no-ip.biz site but now face a
runtime error:

https://groups.google.com/forum/#!msg/python-openzwave-discuss/BfRgDSpzpSk/HcBJvvWMDQAJ
  File "libopenzwave.pyx", line 579, in libopenzwave.PyOptions.**init**
(src-lib/libopenzwave/libopenzwave.cpp:6874)
  File "libopenzwave.pyx", line 582, in libopenzwave.PyOptions.create
(src-lib/libopenzwave/libopenzwave.cpp:6966)
TypeError: expected bytes, str found

So far I have only tried the python-openzwave-0.3.0b5 version.. I'll prob
give the other prev versions a try.

**Comment by TXC** [comment]
I got the "python3" branch compiling withoout errors with:

```
sudo make PYTHON_EXEC=python3 repo-deps
make PYTHON_EXEC=python3 build
sudo make PYTHON_EXEC=python3 install
```

Took a while to figure everything out.

But there seem to be some quirks with gevent and the threading

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/__init__.py", line 365, in _worker
    job = self._work_queue.get().item
  File "/usr/lib/python3.4/queue.py", line 167, in get
    self.not_empty.wait()
  File "/usr/lib/python3.4/threading.py", line 290, in wait
    waiter.acquire()
  File "gevent/_semaphore.py", line 118, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3980)
  File "gevent/_semaphore.py", line 151, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3448)
  File "/usr/local/lib/python3.4/dist-packages/gevent-1.1b5-py3.4-linux-x86_64.egg/gevent/hub.py", line 538, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7feec003b048 epoll pending=0 ref=0 fileno=10>)
```

**Comment by bibi21000** [comment]
There is a problem with the mapping of string in cython, you can look at comment (in french) here : https://github.com/OpenZWave/python-openzwave/commit/530a1cff930d68674af0ce6e2f450dcd98014c5e

@stefan-jonasson : utse the INSTALL_ARC method, it should work on python 3

@txc : can't see a line about python-openzwave in your log ...

@all : 
The author has forked python-openzwave, maybe you can try it

**Comment by partofthething** [comment]
The Home-Assistant folks are forcing an older version of Cython (<0.23), which seems to eliminate the "not an enumerator-name" errors. I am trying to figure out why. One thing I notice is that in the [0.23 changelog](https://github.com/cython/cython/blob/master/CHANGES.rst), they say

> Fixed type errors in conversion enum types to/from Python. Note that this imposes stricter correctness requirements on enum declarations.

The error is referring to the enum's defined in [values.pxd](https://github.com/OpenZWave/python-openzwave/blob/master/src-lib/libopenzwave/values.pxd), which wraps [ValueID.h](https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/value_classes/ValueID.h). Does anyone know a reason these definitions might cause failures of stricter correctness requirements?

**Comment by partofthething** [comment]
I have not figured it out. Here's a collection of related links that might help solve the issue:
- Here is [an unanswered question on the cython-users group](https://groups.google.com/forum/#!searchin/cython-users/class$20enum/cython-users/7wVmQqjFxCs/tKaQFjMohOYJ) about wrapping class enums
- [Here is a PR from cython](https://github.com/cython/cython/pull/437) that may be related to the issue. The authors of this code may be able to help us. 
- [Here is an unanswered StackOverflow question](http://stackoverflow.com/questions/31001918/wrap-enum-class-for-cython) that is probably exactly what we need. 
- [Here is a commit](https://github.com/jcowgill/python-sfml/commit/d8a0b9959f990324e744d2d101cd3e44773b5090) in an unrelated repo that uses cython that [eliminated this error](https://github.com/Sonkun/python-sfml/issues/119) for them
- [Here is a stackoverflow question](http://stackoverflow.com/questions/15561185/wrapping-struct-with-nested-enum-reference-in-vector-template) that uses structs instead of classes but is very related to our issue. 
- Here are the [general instructions for using cython to wrap C++ structures](http://docs.cython.org/src/userguide/wrapping_CPlusPlus.html)

I think our best bet is asking @robertwb for advice.

**Comment by partofthething** [comment]
Aha! I think I got it. With [these changes](https://github.com/partofthething/python-openzwave/commit/0e708b02dd44ec5f6b58b276b971f377c92f4d61), I can build the Cython'd setup-lib.py package using Cython 0.23.3 with Python 3.4. Will have to verify that it still works for earlier Cython versions. If so, I'll send in a PR.

**Comment by bibi21000** [comment]
Sould be fixed. Python3 related

**Comment by bibi21000** [comment]
Should be fixed
