### ISSUE TITLE
(Ubuntu) Failed to build:  unknown file type '.pyx' 

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/python-openzwave#104]
Hi,

I'm following the instructions in the INSTALL_REPO file.

The make repo-deps doesnt exist, so I used make developper-deps instead.

Anyways, when I execute 'sudo make build'

It fails with this error:

error: unknown file type '.pyx' (from 'src-lib/libopenzwave/libopenzwave.pyx')

I don't understand why, I do have Cython installed.

Please help.

Thanks

**Comment by g00dnatur3** [comment]
This is strange, it built successfully on my Kali Linux (3.18.0-kali3-amd64) *python 2.7.3

However on my ubuntu 14.04 (3.16.0-38-generic) *python 2.7.6 -- the build fails

I guess I will try ubuntu 15.04

Hopefully this information helps in debugging

**Comment by bibi21000** [comment]
The make repo-deps doesnt exist, so I used make developper-deps instead : corrected thanks.
Could you please provide the full log of the make build ?
By the way, building with root is always a bad idea

**Comment by g00dnatur3** [comment]
Yeah i normally dont build with sudo, but it wasnt working either way :(

Unfortunately I no longer have the log or anything because i upgraded to ubuntu 15.04 and all is working great!

I was just able to get started coding with your teams beautiful OpenZwave wrapper -- and i dont want to stop now.

Later on I will re-install 14.04 again and reproduce the bug.

thanks

**Comment by bibi21000** [comment]
Non reproductible
