### ISSUE TITLE
Callback error when doing hard reset

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/python-openzwave#105]
Hi,

When I execute a hard reset I get this error:

WARNING:libopenzwave:delValueId : ValueID : 72057594218921988
ERROR:openzwave:Error in manager callback : ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python2.7/dist-packages/pyozwweb-0.3.0b2-py2.7.egg/openzwave/network.py", line 953, in zwcallback\n    self._handle_value_removed(args)\n', '  File "/usr/local/lib/python2.7/dist-packages/pyozwweb-0.3.0b2-py2.7.egg/openzwave/network.py", line 1542, in _handle_value_removed\n    val = self.nodes[args[\'nodeId\']].values[args[\'valueId\'][\'id\']]\n', "KeyError: 'valueId'\n"]

This is my code:
```
def hardReset():
    def callback(state, message, network, controller):
        print('Controller message : %s.' % message)
        return
    dispatcher.connect(callback, ZWaveController.SIGNAL_CONTROLLER)
    network.controller.hard_reset()
    return
```

**Comment by bibi21000** [comment]
It tries to remove a non existing valueid. Not a real problem. 
A reset generates a lot of notifications, It's more safe to start a "new" network after a reset.
Look a pyozman 
HTH

**Comment by g00dnatur3** [comment]
I understand -- but if issue a "hard reset" command, i would expect a to receive a callback to know when the command has completed. Any errors would be passed along in the callback.

Everything is asynchronous - and if i issue a command, i expect to be called back - even if there were errors while executing a command.

To not be called back-- is a bug.

**Comment by g00dnatur3** [comment]
Think about it this way-- in my program design, the client has a button "hard reset" -- a user presses that button. Now the user waits for the command to complete, weather it be 1 second or 10 seconds.

Without a call back, the command is never going to complete- and i have to HACK the program with a kludgey static wait time of like 5 sec before saying "command completed" 

Do you see my point?

**Comment by bibi21000** [comment]
Did you look at code and examples ????

**Comment by g00dnatur3** [comment]
Yes i looked at the hello world example and the api examples.

I am attaching a callback here:

dispatcher.connect(callback, ZWaveController.SIGNAL_CONTROLLER)

is this the correct signal i should listen on when doing a hard reset?

I am not getting called back, when listening on this signal

**Comment by bibi21000** [comment]
bibi21000 commented 9 hours ago
It tries to remove a non existing valueid. Not a real problem. 
A reset generates a lot of notifications, It's more safe to start a "new" network after a reset.
Look a pyozman 
HTH

**Comment by g00dnatur3** [comment]
Ok I will take a look

**Comment by g00dnatur3** [comment]
I looked at ozwave.py pyozwweb app.

I do not see it using louie at all for callbacks.

How can you get away with not using callbacks in an asynchronous api?

Please tell me what i am missing.

I do see in the examples folder, in the hello world example and in the api demo example-- i see you're using louie- i can see you are using the callbacks

All i want is a callback to be guaranteed even if an error happens

Ok ok - i get it, you dont want me to do a hard reset because that is known to have problems--- create a new network instead... this is fine.

but my problem is with not getting called back

**Comment by bibi21000** [comment]
https://github.com/OpenZWave/python-openzwave/tree/master/src-manager/pyozwman
https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/controller.py#L473
