### ISSUE TITLE
There is no guaranteed callback when sending a hard reset command

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/python-openzwave#106]
When i issue a hard reset command to the controller-- yes there are some errors- but a callback is never made to let me know the command has completed.

Its "ok" to have errors, but its not "ok" to not call me back.

Look at any nodejs api-- there is always a callback with an optional errors arg, in case there are errors.

Sometimes there is a success callback and an error callback -- (like in jquery)

But the point being, in any asynchronous api- a callback should be guaranteed unless there is a program crash.

Not being called back is a bug.

**Comment by bibi21000** [comment]
Invalid :A louie signal is generated
Look at code :
https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/controller.py#L473
or documentation :
http://bibi21000.gallet.info/index.php/en/component/sphinxdoc/documentation/3-python-openzwave-api/controller.html
