### ISSUE TITLE
Reading a Home Energy Monitor

### ISSUE THREAD

**Issue by AgustinPelaez** [OpenZWave/python-openzwave#107]
Hello Sébastien,

First of all, thank you for your contribution to the Zwave world through this library. I'm trying to read a Home Energy Monitor sensor and built this code based on your "hello_world.py" example: https://gist.github.com/AgustinPelaez/09ca0b61f0826fa2d3c4

It worked perfectly at first, but then the sensor device just stop sending updates, so the Louie dispatcher can't trigger the functions tied to "ZWaveNetwork.SIGNAL_VALUE".

Am I missing a property to tell the sensor to keep sending updates? or is the hardware just broken?

I was wondering if you could take a look at my code and let me know any suggestion or remarks.

Thanks in advance!

**Comment by bibi21000** [comment]
Hi,
Don't have an energy monitor ... so my help will be limited.
Is your product supported by openzwave ?
A log could be helpfull

**Comment by AgustinPelaez** [comment]
I'm using this gateway as module: Aeon ZStick
And this energy monitor: http://aeotec.com/z-wave-home-energy-measure

I pair them by pressing the button on the USB gateway, then the "pair" button in the energy monitor. They both blink at the same time as if they understand each other, so I'm assuming they are properly paired.

Yes they both are supported by Open Z Wave. I will setup the whole system again and come back to you with a log. Thanks!

**Comment by nechry** [comment]
Check if you have a zwcfgxxx.xml in same folder and also a log file. We can check if inclusion is fully performe.

**Comment by bibi21000** [comment]
no news, good news ...

**Comment by AgustinPelaez** [comment]
Hi guys, I couldn't find the time last weeks to setup my Raspberry Pi but here I am. Better news though; I can tell that the Energy Meter is seen by the library: 

When I run the "hello_world.py" example I get this output, which doesn't show the Energy Meter:

>pi@raspberrypi ~/python-openzwave/examples $ python hello_world.py 
>Openzwave is installed.
>Could Not Open OZW Log File.
>***** Waiting for network to become ready : 
>.INFO:root:Driver ready using library Static Controller version Z-Wave 2.78
>INFO:root:home_id 0x0184e19a, controller node id is 1
>Hello from network : I'm started : homeid 0184e19a - 1 nodes were found.
>..............Hello from network : I'm ready : 2 nodes were found.
>Hello from network : my controller is : home_id: [0x0184e19a] id: [1] name: [Hello name] product: [Z->Stick S2] capabilities: set(['primaryController', 'staticUpdateController']) library: [Static Controller version Z-Wave 2.78]
>***** Network is ready
>Update controller name
>Hello from node : home_id: [0x0184e19a] id: [1] name: [Hello name] model: [Z-Stick S2].
>Update controller location
>Hello from node : home_id: [0x0184e19a] id: [1] name: [Hello name] model: [Z-Stick S2].
>INFO:root:ZWave configuration wrote to user directory.

If I run it again, but press the button in the Energy Meter after the script says "Network is ready", then I immediately see a reading:

>pi@raspberrypi ~/python-openzwave/examples $ python hello_world.py 
Openzwave is installed.
Could Not Open OZW Log File.
***** Waiting for network to become ready : 
.INFO:root:Driver ready using library Static Controller version Z-Wave 2.78
INFO:root:home_id 0x0184e19a, controller node id is 1
Hello from network : I'm started : homeid 0184e19a - 1 nodes were found.
..............Hello from network : I'm ready : 2 nodes were found.
Hello from network : my controller is : home_id: [0x0184e19a] id: [1] name: [Hello name] product: [Z-Stick S2] capabilities: set(['primaryController', 'staticUpdateController']) library: [Static Controller version Z-Wave 2.78]
***** Network is ready
Hello from value : home_id: [0x0184e19a] id: [72057594076479554] parent_id: [2] label: [Power] data: [0.0].
Hello from value : home_id: [0x0184e19a] id: [144115188114407490] parent_id: [2] label: [Power] data: [0.0].
Update controller name
Hello from node : home_id: [0x0184e19a] id: [1] name: [Hello name] model: [Z-Stick S2].
Hello from value : home_id: [0x0184e19a] id: [216172782152335426] parent_id: [2] label: [Power] data: [0.0].
Hello from value : home_id: [0x0184e19a] id: [72057594076496384] parent_id: [2] label: [Exporting] data: [False].
Hello from value : home_id: [0x0184e19a] id: [72057594076495874] parent_id: [2] label: [Energy] data: [495.066009521].
Hello from value : home_id: [0x0184e19a] id: [72057594076495890] parent_id: [2] label: [Previous Reading] data: [495.066009521].
Hello from value : home_id: [0x0184e19a] id: [72057594076495907] parent_id: [2] label: [Interval] data: [14].
Hello from value : home_id: [0x0184e19a] id: [72057594076496384] parent_id: [2] label: [Exporting] data: [False].
Hello from value : home_id: [0x0184e19a] id: [72057594076496002] parent_id: [2] label: [Power] data: [0.0].
Hello from value : home_id: [0x0184e19a] id: [144115188114424320] parent_id: [2] label: [Exporting] data: [False].
Hello from value : home_id: [0x0184e19a] id: [144115188114423810] parent_id: [2] label: [Energy] data: [271.243988037].
Hello from value : home_id: [0x0184e19a] id: [144115188114423826] parent_id: [2] label: [Previous Reading] data: [271.243988037].
Hello from value : home_id: [0x0184e19a] id: [144115188114423843] parent_id: [2] label: [Interval] data: [14].
Hello from value : home_id: [0x0184e19a] id: [144115188114424320] parent_id: [2] label: [Exporting] data: [False].
Hello from value : home_id: [0x0184e19a] id: [144115188114423938] parent_id: [2] label: [Power] data: [0.0].
Update controller location
Hello from node : home_id: [0x0184e19a] id: [1] name: [Hello name] model: [Z-Stick S2].
Hello from value : home_id: [0x0184e19a] id: [216172782152352256] parent_id: [2] label: [Exporting] data: [False].
Hello from value : home_id: [0x0184e19a] id: [216172782152351746] parent_id: [2] label: [Energy] data: [223.822006226].
Hello from value : home_id: [0x0184e19a] id: [216172782152351762] parent_id: [2] label: [Previous Reading] data: [223.822006226].
Hello from value : home_id: [0x0184e19a] id: [216172782152351779] parent_id: [2] label: [Interval] data: [14].
Hello from value : home_id: [0x0184e19a] id: [216172782152352256] parent_id: [2] label: [Exporting] data: [False].
Hello from value : home_id: [0x0184e19a] id: [216172782152351874] parent_id: [2] label: [Power] data: [0.0].
Hello from value : home_id: [0x0184e19a] id: [72057594077773825] parent_id: [2] label: [Battery Level] data: [0].
Hello from node : home_id: [0x0184e19a] id: [2] name: [] model: [Home Energy Meter].
INFO:root:ZWave configuration wrote to user directory.

Maybe I accidentally changed a property inside the Energy Meter in the past, that prevents it from saying "hello" and sending data automatically?

**Comment by AgustinPelaez** [comment]
@nechry indeed there is a log file "zwcfg_0x0184e19a.xml" included in the same directory with this content https://gist.github.com/AgustinPelaez/b949ac74aaf5d370f5b1

**Comment by bibi21000** [comment]
Don't know the delay used by your energy meter  to update its values but the api_sniff example is the a better tool for your problem.
You can find documentation on group assocations in your device documentation, this can help you receive notifications.
You can also try to remove the device from your zwave network and reassociate again. It do the job ... sometimes
Not an issue so close it.

**Comment by AgustinPelaez** [comment]
Thanks Sébastian
