### ISSUE TITLE
cancel_command is deprecated ?

### ISSUE THREAD

**Issue by nechry** [OpenZWave/python-openzwave#109]
hello, you mark the cancel_command in api as deprecated. but is not in openzwave

https://github.com/OpenZWave/open-zwave/blob/f99b8b35307f7bcc5a8e140afe895cf7eaf28574/cpp/src/Manager.h#L1648

https://github.com/OpenZWave/python-openzwave/blob/375c895b8c78d07d13a0edf3b481f4bfa4b4425a/src-api/openzwave/controller.py#L747

is a mistake or you sujest to only use the cancelControllerCommand in lib?

**Comment by bibi21000** [comment]
Don't know if this function is used anymore. 
Will check with justin when he will be back

**Comment by nechry** [comment]
It's actualy the only way to cancel a controler command. If you wan't stop a inclusion or exclusion for example. And in openzwave they don't mark as deprecated.
