### ISSUE TITLE
gevent in python-openzwave

### ISSUE THREAD

**Issue by m0rphi** [OpenZWave/python-openzwave#11]
Hi All,
in the python src-api files for openzwave (command.py, controller.py, network.py etc.) there is **gevent imported with monkey.patch_all()**. I am using **multiprocessing** for another project in python which uses python-openzwave. I am running in errors and It seems to be a general problem   (http://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing). I tried to comment out all gevent imports and run python-openzwave without errors. 
![image](https://cloud.githubusercontent.com/assets/10657553/10189917/790127ce-6769-11e5-9f34-68a0fdaaad9f.png)

My question is: Is it necessary to use gevent in python-openzwave or can I comment it out (without any side effects)?

Thanks in advance for your response ;)

**Comment by bibi21000** [comment]
You can remove them safely. I'll do it in the future

**Comment by m0rphi** [comment]
Just for interest: I´v looked at all src-api files (command.py, controller.py, network.py etc.), no class is using gevent specific methods. 
When it will monkey patched the "normal" behaviour changed a little, and it might be faster with gevent, but are there more benefits in context by using it with python-openzwave?

**Comment by bibi21000** [comment]
the example webapp use socketio + getevent

**Comment by bibi21000** [comment]
Removed
