### ISSUE TITLE
Windows - Python 2.7.14

### ISSUE THREAD

**Issue by kdschlosser** [OpenZWave/python-openzwave#111]
I have managed to get python_openzwave to compile on Windows using python 2.7. I have only done this using 32bit (x86)

This is what I had to do.
fresh install of python 2.7.14
install Cython 0.27.3
install Louie 1.1
install six 1.11.0

    git clone https://github.com/openzwave/python-openzwave.git
    cd python-openzwave
    git checkout

For the next few steps you are going to need the very ancient Visual Studio 10. This is needed to compile openzwave but also to create a new libopenzwave.cpp file.

this next step is going to error out and that is OK for the moment.

    python setup.py build --flavor=embed

you will want to navigate to 
    
python-openzwave\openzwave-embed\open-zwave-master\cpp\build\windows\vs2010

and open OpenZWave.sln with VS2010. then change from debug to release. and build it.. 

Then navigate back to python-openzwave
you are going to want to setup a build environment to use VS2010 to build the new  libopenzwave.cpp file.

    set LOCAL_OPENZWAVE python-openzwave\openzwave-embed\open-zwave-master
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat
    python setup.py build --flavor=dev

once this is done running you will need to copy 

    python-openzwave\src-lib\libopenzwave\libopenzwave.cpp

to 

    python-openzwave\openzwave-embed\open-zwave-master\python-openzwave\src-lib\libopenzwave\libopenzwave.cpp

and back to python-openzwave to run the actual install.

    python setup.py install --flavor=embed

I have not yet fully tested it but it does import without error. I am going to run some tests over the next few hours. Every other attempt at getting it to compile always led to errors or it threw errors when I imported openzwave.network.ZWaveNetwork.

The key is to remake the libopenzwave.cpp file using VS2010 as the compiler. The Python C++ compiled is missing stdint.h but also map.at has not been added until VS2010. and the syntax that is used to build the libopenzwave.cpp file is not compatible with Python C++ so copying the files would simply lead to more errors.

Strange that Cython would use syntax that is not compatible with VC9 when it is installed in python 2.7 but it does. I am not sure if that is an issue with Cython or in the libopenzwave.pyx file. 

*** edit. I forgot a step It has now been added

**Comment by kdschlosser** [comment]
well good news, it seems to be running without error. 

I am pretty sure this process can be simplified and built into the installer. I do not know if following the same procedure with a newer version of C++ will work properly. I should I would imagine. I am going to have to try it.

I will report back if it works.

**Comment by bibi21000** [comment]
Hi
If the process is 'simple', it can be add here : https://github.com/OpenZWave/python-openzwave/blob/master/pyozw_setup.py. 

> Strange that Cython would use syntax that is not compatible with VC9 when it is installed in python 2.7 but it does. I am not sure if that is an issue with Cython or in the libopenzwave.pyx file.
Cython was very "sensible" in the past (under Linux). Never try it under Windows
Thanks

**Comment by kdschlosser** [comment]
It is going to take a while to code it in. this is because the build environment has to be set up. I already know how to launch Visual Studio to compile python openzwave. which is one of the things that the current builder does not do. This I can add no worries. My biggest issue is setting the build environment so cython can compile properly. because you have to build libopenzwave file with the same compiler used to build openzwave.

How come you simply do not distribute a pre compiled libopenzwave?? The reason I ask this is because of the complications involved in locating the different VisualStudio builds in the windows registry. there are bits of information that are needed and the location of them changes based on the version of VS that is installed. (ya gotta love Microsoft and their standards). 

I am going to have to check several of the VS versions to see how they setup the build environment and mimic that. If i am not able to then i will have to run the vcvarsall and the cython build of the cpp file and libopenzwave build from the same subprocess session. If you want I can provide the information you would need and you can code it.. This way it will come out to a standard that is good for you. since you have no way to test it (That is if you do not have Windows still). Up to you.

**Comment by bibi21000** [comment]
No Windows at home for 10 years :) The last I've installed was XP :D 
You can fix a VS version and specify which one must be installed to compile python-openzwave

**Comment by kdschlosser** [comment]
Unfortunately the only one I have been able to get it to compile with is VS 10. The issue is getting your hands on VS 10 is not the easiest thing to do. So I wanted to be able to support a newer version of VS. I am still messing around with it. I am in the process of learning cython

**Comment by bibi21000** [comment]
Hi, I've updated the process for windows installation
Could you test : https://github.com/OpenZWave/python-openzwave/blob/master/docs/INSTALL_WIN.rst

**Comment by kdschlosser** [comment]
Ok this is where I am at.
I am on my mobile device so I do not have the exact traceback handy. I have been working out the kinks in it. There is one left that I am trying to think of a way around it. I can get the build to run properly but I was trying to keep in the spirit of mostly automating it. 

I have tested the builder with phtbon 2.7 thus far. I had to correct how the literal paths we're typed and made use of os.path.join a lot more. I also removed a list being passed to popen as well as the cwd parameter in favor of a formatted command string with complete paths in place. All of this now works without any issues. The issue that I am having is that we need to point distutils to the proper compiler. The same compiler that would be in the VC/bin of the VS install. We need to add 2 environment variables MSSDK and DISTUTILS_USE_SDK I believe the latter is correct or it is something very similar. You can find reference to these I the distutils.msvccompile.py file. If I set these 2 items the first being to the path where the version of cl.exe is matched to the version of msbuild that is being used to compile openzwave the second simply set it to "1" manually at the command prompt before I run the setup everything works just fine. I do not know the inner mechanics of cython or distutils but setting these variables using is.environ before the build takes place or even before cython gets called specifically does not work properly it gets part way. I end up getting cl.exe cannot be found. And when I add the same mssdk path to the PATH environment variable it cannot locate some of the includes which are provided in a windows kit (also another requirement for a build to succeed). I am thinking that the best way to spearhead this crap is to simply only do VS2017 with the Windows 10 SDK and kick the rest to the curb. The reason I state this is because of the very inconsistent manner in which Microsoft has structured the locations of these items (all over the place) this is going to end up being a message of code to try to auomatically add the proper includes. Not unless there is a way to reset the distutils compiler so it can do it's scanning thing. We may even be able to use the distutils compiler to provide the information that is needed to build openzwave. If you can point me in the direction. To access this from inside of the template I can go from there. I do not see a specific object for an instance of something that would do this. It looks as though the template is made and callbacks are passed to distutils. It is so close to working 100% on any version of python it's Killin me.

**Comment by kdschlosser** [comment]
I am using python 2.7 x86 with VS2017 and Windows SDK 8.1 I believe

**Comment by kdschlosser** [comment]
There is also a way we can automatically create an x64 platform and add it to the solution so the user would not have to do this. It would automatically detect the process architecture that python is using and go from there. Can also possibly add a simple cli switch so if the user for some reason wants to do a build for x86 but is running x64 or vice versa it can be done pretty simply. And only add those options if build is specified and run the automatic if no option is supplied or install is used.

**Comment by kdschlosser** [comment]
OK so this is what I have learned.. and also fixed. distutils is broken it does not work properly when using VS 2017 (15.0) It looks for entries for things that are not in the right places. So I coded up a means to do what they were attempting to do except my method is faster as well as it also covers all versions of VS. an the best thing is it sets up an identical build environment that compiling with VS directly would do So no errors. I still do want to make compiling a 64 bit version and also copying the source directory for openzwave all without user interaction. The reason why I would like to see it this way is if someone simply keys in pip install python-openzwave it will do what is needed to get it running. there are way to many new programmers that do not have the experience to do what is needed to make it run. It will also trim down on any support related questions if they do not understand what has to be done.

I am really stoked about finally getting this thing working properly. and it's a shame that distutils does not work properly all on it's own. I may submit a support ticket for it if one has not been submitted. give me another day or so and I will send up a PR for the changes. then you can review them and i can make any changes you feel should be done. I also corrected some other issues with the clean process as well.

The build was successful with Python 2.7.14 x86 running on Windows 7 x64 using VS 2017

**Comment by bibi21000** [comment]
>I have tested the builder with phtbon 2.7 thus far. I had to correct how the literal paths we're typed and made use of os.path.join a lot more. 

Not really needed. Python do it itstelf

>I also removed a list being passed to popen as well as the cwd parameter in favor of a formatted command string with complete paths in place. All of this now works without any issues. 

We can use both methods, not an issue

I've add a new virtual machine with windows 10 on my computer to test. It seems to work well with python 3 (32 and 64bits) and wisual studio 2015/2017. I don't test it with python 2.7.
The important point seems to be to convert the vs2010 config (for vs2015 or vs 2017), that's why I open a PR on openzawe : https://github.com/OpenZWave/open-zwave/pull/1445
With that distutils seem to find all the correct tools to build and link.
I add appveyor continuous integration, and it seems to have a problem to build/link with distutils : https://ci.appveyor.com/project/bibi21000/python-openzwave
Will wait for the decision on the PR for openzwwave. If it is not accepted, I will add these config files directly in python_openzwave.

**Comment by kdschlosser** [comment]
Nope it didn't handle the paths properly. if there is a trailing \ in a literal path and you use os.path.join if ends up being some_path\\some_added_part.

But at any rate. I have sorted all of the problems with it. the larger issues being with python < 3. But they are all sorted out.

In order to get a correct build you have to set up a build environment otherwise the same settings are not used when compiling openzwave and compiling libopenzwave.cpp and that can/will cause issues even if the build complete sucessfully.

This is the basic skinny on what I have done.

instead of iterating through a nested list of possible VS installation directories (someone could install vs in a different location) I have opted to grab the newest version of VS path from the registry. then using this I have it locate msbuild in that installation folder. as well as the VS executable.

If python is x64 and so is windows then I have it modify the sln and vcxproj files to add the needed pieces to have a configuration of x64 (for both Release and ReleaseDLL). then u run devenv with the /Upgrade switch which will upgrade the project to the version of VS that is being used. including the tool chains and any libs things of that nature. This is the most important piece because if these things are not identical to what is used when the libopenzwave.cpp file gets compiled it will throw errors. after the upgrade it then builds openzwave and re creates the libopenzwave.cpp so that it is compatible with the msbuild version that is going to be used. 

I checked with the python bug reports. this problem with VS 2017 not getting detected has been reported. but the fix has only been included in python  >= 3.4. because of this the need to have a mechanism that will auto detect properly is still needed plus i really don't like the way it was fixed. it's overly complicated and uses com objects. this can cause problems if Microsoft changes their API for those objects (which they happen to do a lot).

I am going to do some code cleanup and I am going to remove the use of msbuild for building openzwave and build it with devenv instead this way I am able to combing the upgrade and build into one nice little package and also force it to use the build environment settings instead of what may be in the project.

I will fork python-openzwave and post a link to a finished product by tomorrow night. Then you can decide what you want to do from there.

There is a specific reason why having it compile on python 2.7 is important to me and that is because I am apart of a project called EventGhost which is a windows based HA program. and I would like to add native z-wave control to it. And EventGhost has been around for a very long time and was made with python 2.6. we have upgraded it to 2.7 (with much work) and if we update it to python 3 it is going to be almost a total rewrite (over a million lines of code I would guess), something in which i do not have the time for (or knowledge) at the moment. Plus it would be a good thing to have it compatible with all python versions, It would be able to get used by a much larger group of people and be compatible to HA solutions that already exist and would make it easier for them to add it.

**Comment by kdschlosser** [comment]
One other thing. you can close the PR for the vs project files. The reason for this is there are way to many variables with the project files. if the project files do not have the correct tool chain associated to them there will be issues. doing the upgrade on the users computer will modify the project to use the latest tool chains for the version of vs that is installed. You will understand better when you see the code.

**Comment by kdschlosser** [comment]
well here you go.
https://github.com/kdschlosser/python-openzwave/tree/visualstudio

I have not tested the 64 bit side of things so that still needs to be done. I figured since you are all set up for it you would let me know if it is or is not working.

I need to set up a 32 bit Windows install to locate the reg entries that are needed so that is not working at the moment.

There was a lot of what i would call dead activity on the output someone could think the build process got hung. So I made some modifications to creating the thread to output information to the screen. It provides some output to indicate it is still working.

Be gentle on me with this.. It is a rough draft and could use some work I am sure.

**Comment by kdschlosser** [comment]
This also should work on VS versions from 2008 to 2017 using any combination of available tool chains (Windows SDK's) x64 or x86.

I am not all that concerned about this working on a windows x86 install. they are so far and few between my thoughts on that are upgrade the windows version. or build the library on an x64 Windows box running a 32 bit version of python.

**Comment by bibi21000** [comment]
ok.
Your updates for python 2.7 are important as I will support python 2 AND python 3.
You can submit all the PR you want, so that appveyor and me (windows 10 + python x64) can test them.
This repository is for dev, so if it broken for some days / weeks, it's not a problem.
Common users can install it using pip or a tag.
I will wait for your final updates to release the 0.5 version
I'll delete the PR for openzwave if you think it's not necessary.
If you need to update doc, update them in docs, they will be publish when releasing.
Thanks for your job
