### ISSUE TITLE
keep up to date with openzwave.

### ISSUE THREAD

**Issue by foxsam21** [OpenZWave/python-openzwave#112]
I am having [trouble](https://github.com/OpenZWave/open-zwave/issues/801) that is fixed in the main openzwave. Can we keep up-to-date with the main openzwave? 
I tried copying the manufacturer_specific.xml and the enerwave/zwnrsm2plus.xml files but it is still reported as the rsm1 not rsm2.

**Comment by perosb** [comment]
See issue #105 for a way, if you have that kind of access.
