### ISSUE TITLE
The notification for hard_reset is being called before the command

### ISSUE THREAD

**Issue by g00dnatur3** [OpenZWave/python-openzwave#112]
This is the source code from controller.py:

```
    def hard_reset(self):
        self._network.state = self._network.STATE_RESETTED
        dispatcher.send(self._network.SIGNAL_NETWORK_RESETTED, \
            **{'network':self._network})
        self._network.manager.resetController(self._network.home_id)
```

As you can see the network state and the notification are being sent before the command is sent over the radio.

What if the radio is unable to send the command, what if self._network.manager.resetController has an error? 

I think the correct logic would be to send the command first, then update the network state, and lastly send out notification.

I looked at the openzwave c++ api  and i know there is no notification sent to tell us when exactly the reset has completed (its atleast not documented).

But still, is there a good reason to not send the command before updating state and sending notification?

**Comment by bibi21000** [comment]
- What if the radio is unable to send the command, what if self._network.manager.resetController has an error?
How can this happen ? Did this happen ? Do you have log ?

- I think the correct logic would be to send the command first, then update the network state, and lastly send out notification.
This is your logic

- But still, is there a good reason to not send the command before updating state and sending notification?
Did you try it ? did you read the doc written the lines above your copy/paste :
This command fires a lot of louie signals. Louie’s clients must disconnect from nodes and values signals

As said in docs, GitHub Issues are for bugs, not for people that don't want to read the docs. So please stop spamming Issues with your questions. There is a google group for that (again, the link is in the documentation).
I've spent many hours to write the documentation, I don't want to waste my time in making copy-paste for those that don't want to read it.
