### ISSUE TITLE
POPP 012501 Strike Lock Control device

### ISSUE THREAD

**Issue by gcosta74** [OpenZWave/python-openzwave#113]
As shown in the following link the POP 012501 Strike Lock Control device will not be detected correctly inside python-openzwave:

https://community.home-assistant.io/t/need-help-fibaro-fgpb101-button-popp-012501-strike/7312

What is missing in the on/off-switch or door-lock/unlock object.

At the moment I don't know whether it is a python-openzwave or a home-assistant issue, as it seems that with open-wave and ozwcp the device functions correctly (see also screenshot inside the above mentioned link)
![a343f1358afb95d7b75c39da4ca9769e6bf151a6](https://user-images.githubusercontent.com/18614022/35461940-33ac74c0-02ea-11e8-8a79-966af9810ef9.png)
![a41c92a03f62af962bdddeb0d3328753b8cc84f4_1_690x359](https://user-images.githubusercontent.com/18614022/35461948-3ebce796-02ea-11e8-90ea-4919dfc9b2c4.png)

I have attached the log-file after adding/pairing the node to open-zwave via home-assistant
[install_popp_lock.txt](https://github.com/OpenZWave/python-openzwave/files/1669241/install_popp_lock.txt)

**Comment by gcosta74** [comment]
Just wanted to add the zwcfg.xml entry from open-wave. I shows two missing objects that should normally be in Home-Assistant but they do not show up:

1. COMMAND_CLASS_SENSOR_BINARY
- This is the sensor inside the device for dry input configuration

2. COMMAND_CLASS_DOOR_LOCK
- This should be the door_lock switch to trigger the strike lock

[zwcfg.xml.txt](https://github.com/OpenZWave/python-openzwave/files/1669378/zwcfg.xml.txt)

**Comment by jolaca01** [comment]
Same problem here, no SWITCH entity present, **and from Popp tech support they have told me this**:

> Have you tried to “switch” the device via the DoorLock CC? This class must be supported by the gateway. You can only control the StrikeLock via this CC.

So, it seems that they have confirmed that the 2nd missing object you comment is the IMPORTANT ONE to get it to work.

**Comment by Fishwaldo** [comment]
If the Lock CC is not present then check the device is included Securely.

**Comment by gcosta74** [comment]
Already checked and tried more than once. 
If You look at the attached zwcfg-file and the log You can see that it is definitely a secure connection and if you look carefully at the log you can even find my old zwave security key:

```
<CommandClass id="98" name="COMMAND_CLASS_DOOR_LOCK" version="1" request_flags="4" issecured="true" innif="true" m_timeoutsupported="2" m_insidehandlemode="0" m_outsidehandlemode="0" m_timeoutmins="254" m_timeoutsecs="3">
```

```
2018-01-26 19:02:51.280 Info, Node018, Received SecurityCmd_NonceGet from node 18
2018-01-26 19:02:51.280 Info, NONCES: 0xd4, 0x08, 0x0d, 0x87, 0xab, 0x01, 0x62, 0x11
2018-01-26 19:02:51.280 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.280 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.280 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.280 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.281 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.281 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.281 Info, NONCES: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
2018-01-26 19:02:51.281 Info, Node018, Sending (Security) message (Callback ID=0x01, Expected Reply=0x04) - Nonce_Report - 0x01, 0x11, 0x00, 0x13, 0x12, 0x0a, 0x98, 0x80, 0xd4, 0x08, 0x0d, 0x87, 0xab, 0x01, 0x62, 0x11, 0x05, 0x01, 0x76:
2018-01-26 19:02:51.289 Detail, Node018,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2018-01-26 19:02:51.289 Detail, Node018,   ZW_SEND_DATA delivered to Z-Wave stack
2018-01-26 19:02:51.312 Detail, Node018,   Received: 0x01, 0x07, 0x00, 0x13, 0x01, 0x00, 0x00, 0x02, 0xe8
```

**Comment by jolaca01** [comment]
Mine is also secure now, I also have COMMAND_CLASS_DOOR_LOCK inside my zwcfg-file with issecured="true", as _gcosta74_ one. Still don't have a switch or lock inside HA to operate the device. What can be the reason?? Please help us, thank you!!

**Comment by Fishwaldo** [comment]
Look to see if any ValueAdded Notifications are sent for the Lock CC. If they are then it’s a issue with the HA software you are using and not OZW (at least the base library)

**Comment by jolaca01** [comment]
Please bear with me as I'm noob with all that. Regarding ValueAdded Notifications in my OZW_Log file there are quite a lot for this Node, but it is not detailed for which class they are sent. This is an example of what I have found:
"**Notification: ValueAdded
2018-02-03 16:18:49.118 Detail, Node022, Notification: ValueAdded
2018-02-03 16:18:49.256 Detail**"
Should I look elsewhere??
In my case, there's only a mention of the Lock CC in my OZW_Log file and it is this one:

"**Setting Encryption Flag on Message For Command Class COMMAND_CLASS_DOOR_LOCK
2018-02-03 16:20:53.916 Detail, Node022, Queuing (Send) DoorLockCmd_Get (Node=22)**"

**Comment by bibi21000** [comment]
Try to install the last release of python_openzwave (0.4.4) and launch:

(venvX) pyozw_check -l -d /dev/yourdevice -t 60

It will collect all command_classes available for your node ie : 

------------------------------------------------------------
4 - Name :  ( Location :  )
 4 - Ready : True / Awake : True / Failed : False
 4 - Manufacturer : GreenWave  ( id : 0x0099 )
 4 - Product : PowerNode 6 port ( id  : 0x0004 / type : 0x0003 )
 4 - Version : 4 / Secured : False / Zwave+ : False
 4 - Command classes : {'COMMAND_CLASS_BASIC', 'COMMAND_CLASS_CONFIGURATION', 'COMMAND_CLASS_SWITCH_BINARY', 'COMMAND_CLASS_VERSION', 'COMMAND_CLASS_CRC_16_ENCAP', 'COMMAND_CLASS_MANUFACTURER_SPECIFIC', 'COMMAND_CLASS_ASSOCIATION', 'COMMAND_CLASS_MULTI_INSTANCE/CHANNEL', 'COMMAND_CLASS_METER', 'COMMAND_CLASS_PROTECTION', 'COMMAND_CLASS_NO_OPERATION', 'COMMAND_CLASS_SWITCH_ALL'}
 4 - Capabilities : {'listening', 'routing', 'beaming'}
 4 - Neigbors : {1} / Power level : None
 4 - Is sleeping : False / Can wake-up : False / Battery level : None

**Comment by gcosta74** [comment]
Tried with python_openzwave (0.4.4) and thats the result:

```
24 - Name :  ( Location :  )
 24 - Ready : False / Awake : True / Failed : False
 24 - Manufacturer : Popp  ( id : 0x0154 )
 24 - Product : 012501 Strike Lock Control ( id  : 0x0001 / type : 0x0005 )
 24 - Version : 4 / Secured : False / Zwave+ : True
 24 - Command classes : {'COMMAND_CLASS_DOOR_LOCK', 'COMMAND_CLASS_POWERLEVEL', 'COMMAND_CLASS_VERSION', 'COMMAND_CLASS_MANUFACTURER_SPECIFIC', 'COMMAND_CLASS_ASSOCIATION', 'COMMAND_CLASS_NO_OPERATION', 'COMMAND_CLASS_CONFIGURATION', 'COMMAND_CLASS_ZWAVE_PLUS_INFO', 'COMMAND_CLASS_BATTERY', 'COMMAND_CLASS_BASIC', 'COMMAND_CLASS_USER_CODE', 'COMMAND_CLASS_DEVICE_RESET_LOCALLY'}
 24 - Capabilities : {'frequent', 'routing', 'beaming'}
 24 - Neigbors : set() / Power level : None
 24 - Is sleeping : False / Can wake-up : False / Battery level : 100
```

What bothered me here that it says "24 - Version : 4 / **Secured : False** / Zwave+ : True"
Does this mean the node is not in a secure mode ?

**Comment by gcosta74** [comment]
> Try to install the last release of python_openzwave (0.4.4) and launch:
> 
> (venvX) pyozw_check -l -d /dev/yourdevice -t 60
> 
> It will collect all command_classes available for your node ie :

Do I need to install open-zwave first ?

**Comment by jolaca01** [comment]
But, it has displayed COMMAND_CLASS_DOOR_LOCK. So, is now Door_lock enable as an entity or this command 'pyozw_check'  was just listing the, in theory, available command classes?

**Comment by bibi21000** [comment]
> What bothered me here that it says "24 - Version : 4 / Secured : False / Zwave+ : True"

After looking at c++ code : no. I have made a mistake. I will update that in next release.

> Do I need to install open-zwave first ?

Not needed. Python_openzwave is a wrapperto this lib and embed it. You can modifiy this behavior, read the docs

> But, it has displayed COMMAND_CLASS_DOOR_LOCK. 

COMMAND_CLASS_DOOR_LOCK is recognized in python_openzwave. 

> So, is now Door_lock enable as an entity or this command 'pyozw_check' was just listing the, in theory, available command classes?

Don't know how HA works, check with its developpers for your problem

**Comment by jolaca01** [comment]
Thank you very much for your interest @bibi21000 , we'll try to get an answer from home assistant developers, although noone has comment yet at the HA issue open by @gcosta74 .

**Comment by bibi21000** [comment]
Don't know if that can help but : 
- A user submit à PR for door stuff : https://github.com/OpenZWave/python-openzwave/pull/83 (ofr the 0.4.0) which was accpeted
- Jeedom use an older release of python-openzwave (0.3.x) and seems to use door_lock- command classes.
Maybe HASS developpers can look at code / contact them to know how they use it

**Comment by gcosta74** [comment]
Solution was found within homeassistat.

https://github.com/home-assistant/home-assistant/pull/12951

It was not a openzwave or python-openzwave issue
