### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by gazoscalvertos** [OpenZWave/python-openzwave#119]
Hi everyone,

Trying to run python-openzwave on HA which works fine on python 3.5.2 however I can't get this to run using python 3.5.3. I hit this error:

ImportError: /srv/homeassistant/homeassistant_venv_3.6/lib/python3.5/site-packages/libopenzwave.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

python-openzwave-0.4.4
python 3.5.3

Any ideas?

**Comment by dshanske** [comment]
I have the same problem and haven't been able to solve it.

**Comment by gazoscalvertos** [comment]
There has to be something else causing this on my host box as I have created a docker and it works fine on 3.5.3 and above.  I'm moving over to that so this isn't an issue anymore for me.

**Comment by bibi21000** [comment]
Looking at google, seems to be a problem with cython release (ie https://github.com/kivy/kivy/issues/5453) : 
Try to use cython packaged with your distro, or test with one available on pypi
Hth
