### ISSUE TITLE
How to read/write configuration on a Z-Wave device?

### ISSUE THREAD

**Issue by nowox** [OpenZWave/python-openzwave#121]
I would like to read/write configuration parameters for this device: 

http://nodon.fr/support/NodOn_OctanRemote_ZWave_UserGuide_EN.pdf

The help for `get_config` says `Set config to value`. 

```
In [28]: rocker.get_config?
Signature: rocker.get_config(value_id=None)
Docstring:
The command 0x70 (COMMAND_CLASS_CONFIGURATION) of this node.
Set config to value (using value value_id)

:param value_id: The value to retrieve value. If None, retrieve the first value
:type value_id: int
:return: The level of this battery
:rtype: int
File:      /usr/local/lib/python3.5/dist-packages/openzwave/command.py
Type:      method
```

Unfortunately it seems the command class `COMMAND_CLASS_CONFIGURATION` is empty: 

```
In [34]: rocker.get_values_for_command_class(112)
Out[34]: {}

In [35]: rocker.get_command_class_as_string(112)
Out[35]: 'COMMAND_CLASS_CONFIGURATION'
```

How can I get/read a configuration parameter on a Z-Wave device? I am looking for documentation

It seems the configuration file is not linked to my device: 
https://github.com/OpenZWave/open-zwave/blob/master/config/nodon/crc360xSofremote.xml

```
In [39]: rocker.manufacturer_id
Out[39]: '0x0165'

In [40]: rocker.product_type
Out[40]: '0x0002'

In [41]: rocker.product_id
Out[41]: '0x0002'
```

I have tried this: 

```
In [47]: network.manager.setConfigParam(network.home_id, rocker.node_id, 8, 1, 1)
Out[47]: True

In [48]: network.manager.requestConfigParam(network.home_id, rocker.node_id, 8)

In [49]:
```

But it does not change the behavior of my soft remote.

**Comment by bibi21000** [comment]
That's the way it should work.
I don't have such device so can't really help you

**Comment by dvas0004** [comment]
@nowox I dont know if you still have this issue, but I ran across the same "issue" when setting up a new Fibaro. You are probably looking at the same issue, which is that Openzwave does not recognize your device, and you need to add it manually:

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

I wrote a pretty detailed blog post on how I ended up doing it:

http://blog.davidvassallo.me/2018/12/06/z-wave-lessons-learned-python-openzwave/

It's not a code issue though, so this issue can be closed...

**Comment by nowox** [comment]
@dvas0004 Thanks for the link. I temporarily moved on EnOcean judging Z-Wave too cumbersome, but I will eventually move back to it so I might use your blog post. 

As you said, this is not a issue so I close it for now.
