### ISSUE TITLE
Python-openzwave crashes with limited debug information

### ISSUE THREAD

**Issue by timcoote** [OpenZWave/python-openzwave#122]
I wish that I could get more data on this matter, but I cannot work out how to.

I've got 16 Raspberrypi's + ZWave.me stick with python-openzwave 0.4.4 installed from pypi.  The ZWave network is mostly Fibaro FGMS-001 'eye of Sauron' devices. At varying intervals from an hour or so to a month or so, the OZW stack seems to just stop.  Unfortunately, I have not been able to reproduce this behaviour in any development environment.

Sysstat shows that there is resource contention at the time of crashes, but there is similar resource contention when there is no crash. 

Usbmon shows that the last interaction was from the ZWave stick to the pi.

Crashes are preceded by unusually long series of what look like repeat messages from a single device.

Are these known symptoms, and /or how can I get further and better particulars to help nail where the issue is?

**Comment by bibi21000** [comment]
Sorry for the logn delay
Raspberry are slow computers and everything can happen when system overload.
You can try to use memory swap, and other tips to increase performances of the raspberry ... but don't know if that can help you.
To get more info, you can change the debug level of openzwave when initializing python-openzwave. Don't know if this can help you but this will surely amplify the problem (there will be more logs / io)
HTH

**Comment by timcoote** [comment]
Thanks for the response. RPi's are slow by current standards, but they're faster than my old laptop that used to run windows 4 on a 100Mbps network.

Much of the issue seems to stem from the devices (replacing hardware often removes the failures). I'll work with better logging and reducing the footprint of the rest of the s/w on the pi.
