### ISSUE TITLE
pyozw_shell doesn't work properly only with python3

### ISSUE THREAD

**Issue by lenardteri** [OpenZWave/python-openzwave#127]
Testing the last version, 0.4.8, of python-openzwave lead me to find out that the "old"  ozwsh tool is now called pyozw_shell. The implementation of the pyozw_shell seems to be relatively the same as ozwsh, working fine with python2. But with a installation only using pip3(python3), the pyozw_shell is barely usable, you can not set a value_id !!! due to the fact that the pyozw_shell is implemented in python2 and uses unsupported "long" type cast to convert the value_id when trying to set it to a value.

This issue makes the pyozw_shell unusable with python3 without a additional installation of python2 version.

A possible fix can be to replace the long cast calls with int type cast. Can this be fixed or it is necessary a pull-request for it to be fixed?

**Comment by bibi21000** [comment]
hi
Thanks for your bug reporting.
You're right, there is 4 for remaining long cast in pyozw_shell.
Could you provide a PR ?
I can release a new version in the next few days
Thks

**Comment by lenardteri** [comment]
Hello bibi!

Thanks for answering so quickly. I will, today and commit a pull-request with the changes.

**Comment by lenardteri** [comment]
Made the pull request here: https://github.com/OpenZWave/python-openzwave/pull/128

It seems that some checks were not successfully, it is a problem?

**Comment by bibi21000** [comment]
Tests on travis and cicrle are ok ... So it's ok
Thanks
Other tests are for windows ... But can't finish buid process for windows
Next release will be available in few hours

**Comment by lenardteri** [comment]
Thanks bibi! Have a nice day!
