### ISSUE TITLE
Process blocked on interface reset

### ISSUE THREAD

**Issue by lenardteri** [OpenZWave/python-openzwave#130]
During the hard reset of the z-wave network, the process in which the library runs is suspended for few seconds until the reset is finished. This fact makes other objects/threads running in the same process unable to execute its code or perform its task. 

My question is: Is this behavior from the c++ library or from how the python wrapper interacts with c++ functions/objects? If it is from the python wrapper can we try to fix it?

**Comment by bibi21000** [comment]
I just use the command given by the c++ library. Not more.
Maybe you can put the 'python-openzwave network' in a separate thread.
