### ISSUE TITLE
Multi Instance Command Class

### ISSUE THREAD

**Issue by kdschlosser** [OpenZWave/python-openzwave#135]
This is more of a question then an issue.

I have a Landscape Lighting Controller. It is a central controller as well as a multi instance device

Here are the command classes it supports.
COMMAND_CLASS_SWITCH_ALL
COMMAND_CLASS_SWITCH_BINARY
COMMAND_CLASS_BASIC
COMMAND_CLASS_CONFIGURATION
COMMAND_CLASS_TIME_PARAMETERS
COMMAND_CLASS_NO_OPERATION
COMMAND_CLASS_VERSION
COMMAND_CLASS_MANUFACTURER_SPECIFIC
COMMAND_CLASS_MULTI_INSTANCE/CHANNEL

It has built into it 6 zones that can be switched on and off. This would have to be done with multi instance. 

So my questions are as follows. How do I access getting the state of each of the instances.
and how do i access setting the state for each instance as well.

If anyone knows and can help me out that would be a big help..

**Comment by kdschlosser** [comment]
no one huh??  well that kinda stinks. I really do want to control this thing but I do not know how to access the individual relays on it.

**Comment by kdschlosser** [comment]
Well I have found that it is impossible to access the nested relays or sensors using python-openzwave in it's current state. It is supported in openzwave.

This is what I have determined from looking at the code.

openzwave is broken down into individual command classes and much of the common methods for changing states of the nodes can bee done directly in the manager. python-openzwave was only coded to deal with the manager. it has no knowledge of the individual command classes in openzwave. The bits of code that needs to be accessed can only be done by getting the command class instance for that node. The amount of knowledge I have when dealing with Cython is very limited and making a change like this would require a very large update to the Cython portion of open-zwave.

If there is someone out there that has more experience and is willing to help me out with it that would be awesome.

**Comment by Fishwaldo** [comment]
Different instances are represented in the Instance Integer in each ValueID. There is no need either in the C++ library or any wrapper to ever access any methods on any CommandClasses. 

http://www.openzwave.com/dev/classOpenZWave_1_1ValueID.html#a42a084496f89a18714216432573ced58

**Comment by Fishwaldo** [comment]
Btw, the documentation is not entirely correct. Most CommandClasses can be nested in instances, not just SensorMutliLevel.

**Comment by kdschlosser** [comment]
OK I got ya.. So how would I go about accessing the individual relays for a lighting device that supports  COMMAND_CLASS_MULTI_INSTANCE/CHANNEL???

would I need to know the specific value id's of the relays?

This is what I am trying to accomplish.

The device is a Kichler 15DC300 6 zone landscape lighting controller. I can pair the device no problems. and it provides a single switch variable which acts as an all on and all off for all 6 zones. I have the ability to turn each zone on and off from the front control panel and also from the Z Wave remote that came with the controller. I would like to be able to control the lighting using OpenZwave.

They made a single mistake when they designed the thing. You can save all of the settings for when to turn on and off the different zones. but if you lose power you have to go to the unit and manually restore the setting. Its a pretty big inconvenience because by time I notice that it's not working properly it's usually when I am walking into my house with my arms full and I have no lighting..

It would also be nice to be able to use a program called Find that does location awareness from WiFi signal strength to trigger when I am walking up to a zone and to light it up for me.

**Comment by Fishwaldo** [comment]
Depends on the application, but most listen to the ValueAdded Notification and from there you can check the Instance of the ValueID advertised in the Notification to find the one your interested in.

**Comment by kdschlosser** [comment]
ok so this is what i ended up with

```
2019-03-18 07:06:04.119 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Switch
value instance: 1


2019-03-18 07:06:04.120 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Switch All
value instance: 1


2019-03-18 07:06:04.120 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Library Version
value instance: 1


2019-03-18 07:06:04.121 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Protocol Version
value instance: 1


2019-03-18 07:06:04.122 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Application Version
value instance: 1


2019-03-18 07:06:04.122 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Date
value instance: 1


2019-03-18 07:06:04.123 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Time
value instance: 1


2019-03-18 07:06:04.123 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Set Date/Time
value instance: 1


2019-03-18 07:06:04.124 Detail, Node018, Notification: ValueAdded
product_name: 15DC300
value label: Refresh Date/Time
value instance: 1
```

**Comment by Fishwaldo** [comment]
Are you sure the other zones are implemented? Is this device included with security enabled? If so, try without security. 

Otherwise please send a full OZW log file after removing zwcfg_*.xml.

**Comment by kdschlosser** [comment]
I can do that.

The device is also a zwave controller.

**Comment by kdschlosser** [comment]
here you go.

[OZW_Log.zip](https://github.com/OpenZWave/python-openzwave/files/2978780/OZW_Log.zip)

**Comment by Fishwaldo** [comment]
Node 18?

it was Dead in the Logs you sent me. Didn't respond, so I can't see anything...

**Comment by kdschlosser** [comment]
ok here we go. dunno why it was dead. and I couldn't remove the thing either. I added it again so it is Node19

[OZW_Log.txt](https://github.com/OpenZWave/python-openzwave/files/2979289/OZW_Log.txt)

**Comment by kdschlosser** [comment]
I see the instance numbers now.

So that is how I can change the state of the individual relays...
I need to iterate over the values. look for the proper label and then also check the instances. That is pretty simple to do.

**Comment by kdschlosser** [comment]
@Fishwaldo 

I wanted to say thanks for helping me with that. I do appreciate it.
To be honest with you I really don't know how I managed to miss the multiple switches but I did.

I did want to ask a question of ya. I have been writing a better command class structure for python-openzwave. and as I have been looking over the code for openzwave I noticed that with the user codes for example thee label for the variable has been appended with a digit, is it possible to do the same for multi instances??

The reason I ask this is because this is most likely how I missed it when iterating over the variables I would look for the label "Switch" and then set the value for it and stop the iteration. I have made concessions to better handle variables that are from the same command class that have duplicate names in the python end of things Thought it might be useful to do in openzwave


I also have one other question and this can be answered by @bibi21000 as well. openzwave does not have hard coded support for all of the command classes here are several active command classes COMMAND_CLASS_HUMIDITY_CONTROL_MODE, COMMAND_CLASS_HUMIDITY_CONTROL_OPERATING_STATE,
COMMAND_CLASS_HUMIDITY_CONTROL_SETPOINT

How do these devices get handled? what is the data returned for a variables unit of measure? do you simply return the raw data in it's place since the command class is not defined?

are the indexes of the variables constant across devices that use the same command class?
