### ISSUE TITLE
Failed to install python-openzwave on Python 3.7

### ISSUE THREAD

**Issue by zajnic** [OpenZWave/python-openzwave#140]
Hi,

I am not able to install python-openzwave on Python 3.7. here is the error. Anyone know how to fix it?

    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/command.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/controller.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/option.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/object.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/scene.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/network.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/singleton.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/group.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/value.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    copying src-api/openzwave/node.py -> build/lib.macosx-10.9-x86_64-3.7/openzwave
    creating build/lib.macosx-10.9-x86_64-3.7/pyozwman
    copying src-manager/pyozwman/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/pyozwman
    copying src-manager/pyozwman/ozwsh_widgets.py -> build/lib.macosx-10.9-x86_64-3.7/pyozwman
    copying src-manager/pyozwman/ozwsh_main.py -> build/lib.macosx-10.9-x86_64-3.7/pyozwman
    creating build/lib.macosx-10.9-x86_64-3.7/python_openzwave
    copying src-python_openzwave/python_openzwave/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/python_openzwave
    creating build/lib.macosx-10.9-x86_64-3.7/python_openzwave/ozw_config
    copying src-python_openzwave/python_openzwave/ozw_config/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/python_openzwave/ozw_config
    creating build/lib.macosx-10.9-x86_64-3.7/python_openzwave/scripts
    copying src-python_openzwave/python_openzwave/scripts/pyozw_check.py -> build/lib.macosx-10.9-x86_64-3.7/python_openzwave/scripts
    copying src-python_openzwave/python_openzwave/scripts/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/python_openzwave/scripts
    copying src-python_openzwave/python_openzwave/scripts/pyozw_shell.py -> build/lib.macosx-10.9-x86_64-3.7/python_openzwave/scripts
    running build_ext
    cythoning src-lib/libopenzwave/libopenzwave.pyx to src-lib/libopenzwave/libopenzwave.cpp
    building 'libopenzwave' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/src-lib
    creating build/temp.macosx-10.9-x86_64-3.7/src-lib/libopenzwave
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DPY_LIB_VERSION=0.4.10 -DPY_SSIZE_T_CLEAN=1 -DPY_LIB_FLAVOR=git -DPY_LIB_BACKEND=cython -Iopenzwave-git/open-zwave-master/cpp/src -Iopenzwave-git/open-zwave-master/cpp/src/value_classes -Iopenzwave-git/open-zwave-master/cpp/src/platform -Iopenzwave-git/open-zwave-master/cpp/build/mac -I/Users/zachwong/Documents/homeassistant/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src-lib/libopenzwave/libopenzwave.cpp -o build/temp.macosx-10.9-x86_64-3.7/src-lib/libopenzwave/libopenzwave.o -stdlib=libc++ -mmacosx-version-min=10.7
    src-lib/libopenzwave/libopenzwave.cpp:3:9: warning: 'PY_SSIZE_T_CLEAN' macro redefined [-Wmacro-redefined]
    #define PY_SSIZE_T_CLEAN
            ^
    <command line>:3:9: note: previous definition is here
    #define PY_SSIZE_T_CLEAN 1
            ^
    src-lib/libopenzwave/libopenzwave.cpp:32283:60: warning: 'BeginControllerCommand' is deprecated [-Wdeprecated-declarations]
      __pyx_t_6 = __Pyx_PyBool_FromLong(__pyx_v_self->manager->BeginControllerCommand(__pyx_t_1, __pyx_t_2, __pyx_f_12libopenzwave_ctrl_callback, ((void *)__pyx_v_pythonfunc), __pyx_t_3, __pyx_t_4, __pyx_t_5)); if (unlikely(!__pyx_t_6)) __PYX_ERR(0, 4207, __pyx_L1_error)
                                                               ^
    openzwave-git/open-zwave-master/cpp/src/Manager.h:1732:3: note: 'BeginControllerCommand' has been explicitly marked deprecated here
                    DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = NULL, void* _context = NULL, bool _highPower = false, uint8 _nodeId = 0xff, uint8 _arg = 0 );
                    ^
    openzwave-git/open-zwave-master/cpp/src/Defs.h:58:35: note: expanded from macro 'DEPRECATED'
    #define DEPRECATED __attribute__((deprecated))
                                      ^
    2 warnings generated.
    g++ -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.7/src-lib/libopenzwave/libopenzwave.o openzwave-git/open-zwave-master/libopenzwave.a -o build/lib.macosx-10.9-x86_64-3.7/libopenzwave.cpython-37m-darwin.so -framework CoreFoundation -framework IOKit
    clang: error: no such file or directory: 'openzwave-git/open-zwave-master/libopenzwave.a'
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------

**Comment by Colecf** [comment]
I had this same issue. It's an error with building libopenzwave, not python-openzwave, and the output of that build is not in this log, so it's a little more difficult to track down.

It looks like the error is already fixed in open-zwave, but a temporary workaround until this python-openzwave picks up a newer version is to start a build so it downloads and extracts open-zwave, then cancel it and go to `openzwave-embed/open-zwave-master/cpp/build/Makefile`, and add `-Wno-unused-private-field` to the end of line 37.

If you are using home assistant, it appears that it still tries to download python_openzwave version 0.4.9. Opening `/path/to/homeassistant/components/zwave/__init__.py` and changing the required version to 0.4.10 on line 38 stopped it from downloading python_openzwave and trying to build it itself and instead it started using the custom installed version.

**Comment by zajnic** [comment]
Reading through the https://github.com/OpenZWave/python-openzwave
Solved my problem installing pyhton-openzwave with:

(venvX) pip install cython wheel six
(venvX) pip install ‘PyDispatcher>=2.0.5’
(venvX) pip install python_openzwave --no-deps --install-option="–flavor=git"
