### ISSUE TITLE
Flavor ozwdev fails to install

### ISSUE THREAD

**Issue by uchagani** [OpenZWave/python-openzwave#143]
Running the following command to install `pip3 install --no-cache-dir python_openzwave --install-option="--flavor=ozwdev"`

I'm getting the following error:

```
g++: error: openzwave-git/open-zwave-Dev/libopenzwave.a: No such file or directory
error: command 'g++' failed with exit status 1
```

**Comment by uchagani** [comment]
the problem here is that the latest commit on OZW dev branch is causing a build failure.  after going back one commit everything works as expected however you have to use the `dev` flavor when installing and you have to point to your local ozw source code.

**Comment by uchagani** [comment]
This is the PR that is causing problems in the Dev branch: https://github.com/OpenZWave/open-zwave/pull/1558


here are some instructions on how to get passed this issue:

```
git clone https://github.com/OpenZWave/open-zwave.git
cd open-zwave
git checkout Dev
git checkout 666ac0e779ef1585dc0e240ac49239f24ba71c34
```

get the path of the dir with `pwd` then install python_openzwave

```
LOCAL_OPENZWAVE={YOUR_PATH_HERE} pip3 -v install python_openzwave --install-option="--flavor=dev"
```

**Comment by bibi21000** [comment]
Thanks
