### ISSUE TITLE
OZW 1.6 branch?

### ISSUE THREAD

**Issue by kklem0** [OpenZWave/python-openzwave#144]
Shall we make a branch for OZW 1.6 (Dev) branch so we can start putting things in? Like BitSet?

**Comment by Fishwaldo** [comment]
I would hope so. I know many apps are dependent upon the python wrapper so supporting the dev branch and allowing these apps to test the new functionality would give me a lot more confidence when it’s time to release the Dev branch to master. 

I’m happy to advise what, if any other changes in dev may (or may not) require changes to wrappers.

**Comment by bibi21000** [comment]
The Dev branch is available using the zwdev flavour.
We can create a separate dev branch here but it will not be available using pip.
Maybe better to add it to master branch ...
