### ISSUE TITLE
Unable to set temperature on Devolo thermostat

### ISSUE THREAD

**Issue by dereisele** [OpenZWave/python-openzwave#146]
Hello, I'm trying to build a Z-Wave to MQTT gateway and I've noticed that python-openzwave is unable to set both the cooling and heating temperature. 
Than I found out that the labels of these values are `Heating` and `Cooling` instead of `Heating 1` and `Cooling 1`. These "bugs" are [here](https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/command.py#L838) and [there](https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/command.py#L855).
A possible solution would be replacing the simple comparison with a tuple of possible values and later some pattern matching.

**Comment by bibi21000** [comment]
Thank you
