### ISSUE TITLE
set_usercode_at_index only sets first code if run multiple times in loop

### ISSUE THREAD

**Issue by zachfeldman** [OpenZWave/python-openzwave#164]
So, I have a weird problem with `set_usercode_at_index`. It works great in this method definition, even if I run this method multiple times being called from a Flask endpoint, it sets the codes at the index set:

```
  def set_code(self, user_id, code):
    for node in self.network.nodes:
      for val in self.network.nodes[node].get_doorlocks():
        if int(user_id) < 1 or int(user_id) > 30:
          return "Invalid User ID"
        print("Changing code to:", code)
        self.network.nodes[node].set_usercode_at_index(int(user_id), code)
        time.sleep(5.0)
        user_codes = Zwaveserver.view_codes(self)
        code_id = "[Code " + str(user_id) + ":] "
        if str(code) in user_codes[code_id]:
          return "True"
        else:
          return "False"
```

However, the method we have to set multiple codes, `set_codes`, also run from a Flask endpoint, only sets the first index:

```
def set_codes(self, codes):
    for node in self.network.nodes:
      for val in self.network.nodes[node].get_doorlocks():
        code_list = codes.split(',')
        user_id = 1
        it1, it2 = itertools.tee(code_list, 2)
        for code in it1:
          print("Setting code " + code)
          self.network.nodes[node].set_usercode_at_index(int(user_id), code)
          user_id += 1
        codes_set = "True"
        user_id = 1
        print("Getting all codes:")
        time.sleep(5.0)
        user_codes = Zwaveserver.view_codes(self)
        print("Retrieved codes:")
        for code_check in it2:
          code_id = "[Code " + str(user_id) + ":] "
          print("code_id = " + code_id + " code = " + user_codes[code_id])
          if code_check not in user_codes[code_id]:
            codes_set = "False"
          user_id += 1
        return codes_set
```

I have tried adding a 5-10 second timeout in the loop in between sets but that doesn't work.

Any idea if this is a common problem? Or is it maybe a problem with our implementation? Is there maybe a method to set multiple codes/indexes at one time that's internal to the lib that I'm missing?

Thanks for any pointing in the right direction!

**Comment by kdschlosser** [comment]
I do not have a keycode based lock or anything that uses that command class. But I would imagine it would work much like Multi Instance in that respect.

I am curious to know what the value labels are as well as their instance numbers.

if you can iterate over the variables for that device like so. You will need to know what the node id is of  the doorlock to use the code below. change the node_id to the id of the doorlock.

```python
node_id = 0123456789

node = network.nodes[node_id]
for value in node.values.values():
    print(node.label, node.instance, node.index)
```

this is not going to print any codes just the variable name the variable instance number and the index of the variable stored on the node.  a zwave device can have more then a single variable with the same name that is why the instance attribute is available. so there is a way to distinguish them. This is also going to tell us if it is an issue with python_openzwave or libopenzwave. we need to see if it is properly enumerating all of the codes. once we know that we can attempt to set the code directly by using the instance number.

In the next release of openzwave we hope to have a completely redesigned way of handling devices that is going to provide improved command class handling as well as better access to specific types of values that are only available for that specific command class. I do however want to get to the root of this problem that way the same issue does not exist in the new code as well.

**Comment by zachfeldman** [comment]
Figured it out!

It was because I sending 1111, 2222, 3333, etc. I needed to send 1111,2222,3333 without the spaces instead...silly me! This was only due to our implementation too. Thanks so much @kdschlosser for your help.

**Comment by kdschlosser** [comment]
thank you for the update as well as the information. this is something that can be handled very easily by python_openzwave so the issue does not arise again.
