### ISSUE TITLE
data in ZWaveValue Object

### ISSUE THREAD

**Issue by m0rphi** [OpenZWave/python-openzwave#17]
Hi All,

I inspected in python-openzwave the ZWaveValue Objects which are under the Nodes Objects.
In the data field, there is sometimes an unicode, especially on configuration parameters.

E.g. the **Fibaro FGMS001 Motion Sensor** has a config parameter called "LED indicating tamper alarm".
It saves in the **data** field the unicode string instead of an integer.
![image](https://cloud.githubusercontent.com/assets/10657553/10651349/51b62448-784f-11e5-9d5a-19e3a1e33dda.png)

Instead of a unicode in the data field , I wanted to save the integer value, like:
![image](https://cloud.githubusercontent.com/assets/10657553/10651463/fc148aa6-784f-11e5-867a-3d9d9d165dd6.png)

The background: When setting parameters i use the set_config_param method (where the value to set has an integer,too).  I recognize when the config value has changed and I want to save this. But instead of an unicode, I want to save the integer value, which I have set via set_config_param before.

Just tried **data_items** field in the ZWaveValue Object to get the integer value, but this is a "set", so an unordered collection, without an index.

I checked openzwave, and when the node is configured, the integer will be send, but it will not be forwarded to python-openzwave as an integer. Instead you get sometimes the unicode, like in the first picture.
![image](https://cloud.githubusercontent.com/assets/10657553/10651794/ce99f122-7851-11e5-9822-49eee66fe63b.png)

Has someone an idea how to get in this situation an integer value instead of an unicode value?
Thanks in advance!

**Comment by bibi21000** [comment]
Look at the type of the value : you've got one with a byte (or integer) type and the other one is a list.
Data_items is the list of valid strings for this value.

> Has someone an idea how to get in this situation an integer value instead of an unicode value?
> If you really want it, you can map it your self using a dict

**Comment by m0rphi** [comment]
Hi bibi,
thanks for your answer!
Maybe my question was a little bit confusing ;)

Here is a sample use case:
I set a config parameter via set_config_param method, 
(like **set_config_param(param = 1, value = 2 , size = 2**)
The value/data to set is here 2.

When the node wakes up and config parameter are set successfully, I see in the python console (I just print out what louie gives me):

_Value Changed : ID on Network: 0161f8dc.87.70.1.89 || Node: home_id: [0161f8dc] id: [87] name: [] model: [FGMS001 Motion Sensor] || home_id: [0161f8dc] id: [72057595507770772] parent_id: [87] label: [LED indicating tamper alarm] **data: [LED does not indicate tamper alarm.]**_

The **data** field is now a string/list, instead of an integer. 
In my case when a config value has changed, I want to have always an integer value (instead of a list or other datatypes).
Should look like: 
_Value Changed : ID on Network: 0161f8dc.87.70.1.89 || Node: home_id: [0161f8dc] id: [87] name: [] model: [FGMS001 Motion Sensor] || home_id: [0161f8dc] id: [72057595507770772] parent_id: [87] label: [LED indicating tamper alarm] **data: 2**_

Maybe this behavior could also come from openzwave, which bypass the value as a list/string instead of an integer, but I am not sure.

**Comment by bibi21000** [comment]
Sorry but English is not my natural language, so it's not so easy for me :)
Will try to explain again.
Looking at first image (value *_865) : you set|get the config parameter to|as a byte.
You don't report it on the screenshot but look at the type of this value : https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/value.py#L214
It should be 1 : https://github.com/OpenZWave/python-openzwave/blob/master/src-lib/libopenzwave/values.pxd#L31
That's why you read or write byte data to it
Looking at the the second image (value *_260) : you get (as it's a motion sensor) a value of type 4 (ValueType_List). It's a 'fixed' string as it's limited to the values in data_items.
For a write example of this, look at the "switch all" command_class (COMMAND_CLASS_SWITCH_ALL) or protection(COMMAND_CLASS_PROTECTION)
Hope this helps

**Comment by bibi21000** [comment]
Ooops I forgot this : 
Everything come from opezwave :). Python-openzwave is only a wrapper to this lib. The api is here to provide a network to access nodes and values in a "simple" way.
The only specific part is https://github.com/OpenZWave/python-openzwave/blob/master/src-api/openzwave/command.py.
