### ISSUE TITLE
Python 3 config path TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by joshughes** [OpenZWave/python-openzwave#28]
With python3 I am seeing the following issue... 

``` python

    options = ZWaveOption(
        config[DOMAIN].get(CONF_USB_STICK_PATH, DEFAULT_CONF_USB_STICK_PATH),
        user_path=hass.config.config_dir,
        config_path=str(config[DOMAIN].get('config_path',
                                       DEFAULT_ZWAVE_CONFIG_PATH),))

```

```
  File "/home/homeassistant/.pyenv/versions/3.4.2/lib/python3.4/site-packages/openzwave-0.3.0b8-py3.4.egg/openzwave/option.py", line 76, in __init__
    libopenzwave.PyOptions.__init__(self, config_path=config_path, user_path=user_path, cmd_line=cmd_line)
  File "libopenzwave.pyx", line 579, in libopenzwave.PyOptions.__init__ (src-lib/libopenzwave/libopenzwave.cpp:6874)
  File "libopenzwave.pyx", line 582, in libopenzwave.PyOptions.create (src-lib/libopenzwave/libopenzwave.cpp:6966)
TypeError: expected bytes, str found
```

I compiled from source using the [INSTALL_ARCH.txt](https://github.com/OpenZWave/python-openzwave/blob/master/INSTALL_ARCH.txt) method. 

I have compiled from source multiple times and can't seem to actually get this to work... I am wondering if it my be a CYthon issue. 

The Cython version is... 

Cython (0.22)

I also tried to compile from the master branch and not using that INSTALL_ARCH.txt method... It installed but I see the exact same issue.

**Comment by joshughes** [comment]
I was able to fork the repo and hack my way through this. 

https://github.com/joshughes/python-openzwave

I don't think this is PR worthy because i don't think it will support python 2 and 3. Hopefully it gives someone some idea of what is going on though... basically I replaced anything with string(s) with str.encode(s) and added a few methods I found from the following threads. 

https://groups.google.com/forum/#!msg/cython-users/ofT3fo48ohs/rrf3dtbHkm4J

http://docs.cython.org/src/tutorial/strings.html

**Comment by partofthething** [comment]
I don't think this is an issue with Cython 0.23 thanks to [some fixes](https://github.com/cython/cython/blob/master/CHANGES.rst) they made in that version. With Cython 0.23 and Python 3.4, the `python3` branch compiles just fine without the changes @joshughes made here once the changes suggested in #10 are made. 

EDIT: Nevermind: mine compiled but did not run. @joshughes changes got it running for me. Cool.

**Comment by davidkuehner** [comment]
I ran exactly into the same issue as @joshughes  today. 
I compiled from source using the INSTALL_ARCH.txt method too.

**Comment by partofthething** [comment]
Hi @davidkuehner, I saw your comment on my blog. Try running `git checkout python3` before building and you might get around this issue.

**Comment by bibi21000** [comment]
Sould be fixed. Python3 related
