### ISSUE TITLE
Sources cannot be downloaded

### ISSUE THREAD

**Issue by ArjanM83** [OpenZWave/python-openzwave#39]
Following the INSTALL_ARCH.txt:

> You are now ready to download sources of python-openzwave here :
> http://bibi21000.no-ip.biz/python-openzwave/
> This archive contains sources of python-openzwave and openzwave.

This website is not reachable. Any other place to download the sources?

**Comment by Landrash** [comment]
Your on it =) https://github.com/OpenZWave/python-openzwave & https://github.com/OpenZWave/open-zwave

**Comment by ArjanM83** [comment]
I'm trying to use python-openzwave in Windows, at the website of Pytomation I read this:

> Aeon Labs Z-Wave requires python-openzwave, which must be compiled from source. It's highly recommend you use the archived source code. Version 3.0+ no longer requires Cython, which was the source of most of the build/seg fault issues with python-openzwave.

But when I use:
`git clone https://github.com/OpenZWave/python-openzwave.git`

And then:
`python setup-lib.py`

I get this error:

```
Traceback (most recent call last):
  File "setup-lib.py", line 30, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
```

This shows I still need Cython, which should not be required in version 3.0+ (following Pytomation).
So I was assuming I would need the archived source code.
Where do I go wrong here?

**Comment by bibi21000** [comment]
> This website is not reachable. Any other place to download the sources?

My server's UPS is down. I receive a new battery today, It will be up in the next days.
Sorry for that

**Comment by Viish** [comment]
Any update on that specific issue ? Can't compile it on my rpi...

**Comment by Viish** [comment]
Ok so I've been able to compile it on my computer, then I did a `make archive/python-openzwave-0.3.0b8` followed by `make tgz` and tada!! 
The INSTALL_ARCH procedure worked like a charm on my RPi (generated tgz is in dists/python-openzwave-0.3.0b8.tgz)
Cheers!

**Comment by bibi21000** [comment]
Buy a new battery for my UPS but the server seems to be out too. Don't have the time to look at it for now.
All the tools for building packages are included on github (except my ftp password :) ) 
You can build the tar on your computer and install it on your raspberry.

**Comment by bibi21000** [comment]
Archives are available directly in github.
