### ISSUE TITLE
Won't build on Mac OS X

### ISSUE THREAD

**Issue by liber-8** [OpenZWave/python-openzwave#41]
Hi,

has someone successfully build this package under Mac OS X?

Seems like there's no udev lib for OS X and so the build process breaks because of this missing dependency.

Any help is appreciated, thanks!

**Comment by bibi21000** [comment]
Hi
Look at the part 

> elif platform_system() == 'darwin':
>     ext_modules = [Extension("libopenzwave",
>                              sources=["src-lib/libopenzwave/libopenzwave.pyx"],
>                              libraries=['udev', 'stdc++'],
>                              language="c++",
>                              extra_link_args=['-framework', 'CoreFoundation', '-framework', 'IOKit'],
>                              extra_objects=['openzwave/libopenzwave.a'],
>                              include_dirs=['openzwave/cpp/src', 'openzwave/cpp/src/value_classes', 'openzwave/cpp/src/platform', 'openzwave/cpp/build/mac', "src-lib/libopenzwave"]
>     )]

in setup-lib.py.
You can remove the dependance to udev but you may need to add something instead. You can look at the openzwave issues or group to find additionnal informations.

**Comment by liber-8** [comment]
Thanks for your reply, this fixed the UDEV issue in the build process.

I follow the installation instructions from https://home-assistant.io/components/zwave/ :

```
$ git clone https://github.com/OpenZWave/python-openzwave.git
$ cd python-openzwave
$ git checkout python3
$ PYTHON_EXEC=`which python3` make build
$ sudo PYTHON_EXEC=`which python3` make install
```

The build process runs with no errors (3 warnings are generated).

But the install process does not complete and generates this error:

```
  File "/tmp/easy_install-6y8tlbhe/gevent-1.0.2/setup.py", line 111, in make_universal_header
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
make: *** [install] Error 1
```

Any idea how to fix this?

Thanks

**Comment by bibi21000** [comment]
Thanks I've update the setup-lib for Darwin.
You don't need to use the python3 branch anymore. I've fix the bad PR and unified again sources for python 2/3

The error is normal as gevent-1.0.2 is not python 3 compatible.
I've update the dependance to the new 1.1.1 version, which should be compatible with python3. 

You don't need to install the all packages of python-openzwave unless you need them. If you only need the api, you could simply install the api:
sudo PYTHON_EXEC=`which python3` make install-api

**Comment by liber-8** [comment]
Great thanks!

The gevent error is gone and the build process runs fine (besides 3 warnings).

The install process did again stop with an udev error:

```
15 warnings generated.
creating build/lib.macosx-10.6-intel-3.5
/usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.5/src-lib/libopenzwave/libopenzwave.o openzwave/libopenzwave.a -ludev -lstdc++ -o build/lib.macosx-10.6-intel-3.5/libopenzwave.cpython-35m-darwin.so
ld: library not found for -ludev
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit status 1
make: *** [install-lib] Error 1
```

I manually removed the udev dependency for ext_modules in line 117 (setup-lib.py) and the install process did complete without errors.

I still have to check if my USB stick / devices are recognised and can be used with Home Assistant but it looks very promising. Update follows..

Again thanks for your support.

**Comment by bibi21000** [comment]
Could you copy/paste the result of : 
python -c "from platform import system as platform_system;print platform_system()"
TIA

**Comment by liber-8** [comment]
Sure:

```
$ python -c "from platform import system as platform_system;print platform_system()"
Darwin
```

Capital 'D'...

**Comment by liber-8** [comment]
I replaced 'darwin' with 'Darwin' in setup-lib.py and udev errors are gone.

But no luck with Home Assistant:

```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/libopenzwave-0.3.0b8-py3.5-macosx-10.6-intel.egg/libopenzwave.cpython-35m-darwin.so, 2): Symbol not found: __ZN9OpenZWave7Manager11SetNodeNameEjhRKSs
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/libopenzwave-0.3.0b8-py3.5-macosx-10.6-intel.egg/libopenzwave.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/libopenzwave-0.3.0b8-py3.5-macosx-10.6-intel.egg/libopenzwave.cpython-35m-darwin.so
```

**Comment by bibi21000** [comment]
Not linked to Home-assisant ... if you were on linux, I should say that the openzwave libray seems to be dynamically linked ... but it in the setup-lib.py we build a statically linked version. Maybe Darwin don't like that ...
Don't knwon if it should work but : 
Update line 78 to : 
     libraries=['setupapi', 'stdc++', 'openzwave'],
Then : 
make build
then
cd openzwave
and
sudo make install
The previous command should install the c++ library (.so?).
You may need to launch something like :
sudo ldconfig
After return to python-openzwave directory and
sudo make install

And maybe it should work ... 

If you succeed it should be nice if you could update the documentation (docs/INSTALL_MAC.rst) with the full installation process.
You can use INSTALL_REPO.rst as a template but ... it's for ubuntu/debian :)
If you want to go further, you can generate the documentation with make docs and add the new generated files in docs/ to git.
Thanks in advance

**Comment by liber-8** [comment]
Here's what I did:

Edited line 86: libraries=['stdc++', 'openzwave'],

setupapi is not available for OS X, seems to be a Windows library.

Then `PYTHON_EXEC=`which python3` make build`, `cd openzwave` and `sudo make install`.

Got this error:

```
Installing Pkg-config Files
install: chmod 755 //usr/lib/pkgconfig: Operation not permitted
cp: //usr/lib/pkgconfig/libopenzwave.pc: Operation not permitted
make[1]: *** [install] Error 1
make: *** [install] Error 2
```

I had to disable SIP (System Integrity Protection) to get rid of it.

ldconfig is also not available for OS X so I skipped this step.

Back to python-openzwave and did `sudo PYTHON_EXEC=`which python3` make install`.

In the end I got the same error message in Home Assistant.

I did some Google search.. I'm by no means a pro developer and honestly have no idea what the command does exactly but it sounded like I should give it a try :-)

`sudo libtool -dynamic /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/libopenzwave-0.3.0b8-py3.5-macosx-10.6-intel.egg/libopenzwave.cpython-35m-darwin.so -o /usr/local/lib/libopenzwave-1.4.dylib -framework CoreFoundation`

but with no success:

```
ld: warning: -macosx_version_min not specified, assuming 10.10
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/libopenzwave-0.3.0b8-py3.5-macosx-10.6-intel.egg/libopenzwave.cpython-35m-darwin.so' for architecture i386
fatal error: /Library/Developer/CommandLineTools/usr/bin/libtool: internal link edit command failed
```

Replacing the -dynamic parameter with -static does not throw an error but does not work either.

Anything else you can think of being worth a try?

Thanks.

**Comment by bibi21000** [comment]
Sorry. No more idea.
Try to look at openzwave group

**Comment by liber-8** [comment]
OK, no worries. I can still run it in a Docker container till someone shows up and knows how to get it running.

I already filed in a request in the OZW group and in the Home Assistant forum..

Thanks for your help :-)
