### ISSUE TITLE
Binary switch value inverted ?

### ISSUE THREAD

**Issue by Viish** [OpenZWave/python-openzwave#47]
Hi,

I just noticed something weird. I'll take the examples/hello_world.py file as reference to simplify.
When the script does the 'Activate switch' part, it does a set_switch(val,True) to turn the switch on. So far, everything is fine.
Problem is, in the louie_value_update callback, the current value (for the switch turned on) is False:
Hello from value : home_id: [0x01852cfc] id: [72057594093060096] parent_id: [3] label: [Switch] data: [False].
Same thing again when the script disable the switch with set_switch(val,False), the callback says the switch data is True.

Is this normal in the ZWave protocol or is this an issue ?

Cheers.

**Comment by Viish** [comment]
Hum, this is weird.

I've done some more tests, and the value in the callback is wrong only the first time.
If I do set_switch(val, True), the callback says the value is False. If I do it again, this time the value is True. Same goes with set_switch(val, False).

Is this an issue in the library of with my hardware ? I have a Fibaro wall plug.

**Comment by nechry** [comment]
Is somerhing interesting, many fibaro wallplug complain about somerhing like this.

Try also with ozw control panel and check is same issue 

JF

**Comment by Viish** [comment]
Same thing happens with OZW Control Panel (see logs attached)
[ozwcp_logs.txt](https://github.com/OpenZWave/python-openzwave/files/240774/ozwcp_logs.txt)

This line makes it obvious:
2016-04-28 16:51:54.754 Detail, Node003, Refreshed Value: old value=true, new value=true, type=bool

**Comment by Viish** [comment]
Any update regarding this issue ?

**Comment by bibi21000** [comment]
Problem related to openzwave config paraeters
