### ISSUE TITLE
DeprecationWarning in Manager 

### ISSUE THREAD

**Issue by m0rphi** [OpenZWave/python-openzwave#5]
Hi,

thanks for fixing the previous bug with the AttributeError bibi!
I builded and installed python-openzwave again(details about my system below) and started the manager ozwsh in `/root/dev-python-openzwave/build/manager/scripts-2.7`
![send add_device](https://cloud.githubusercontent.com/assets/10657553/8766869/25b478d6-2e49-11e5-81af-2ca2f4668b47.PNG)

After executing e.g. send add_device command, the management console got broken with the following message: **_ozwsh_widget.py:1107: DeprecationWarning: Call to deprecated function begin_command_add_device.**_ (see the last lines in the next picture)
![send add_device after execution](https://cloud.githubusercontent.com/assets/10657553/8766876/4746b7ca-2e49-11e5-8356-79b1cfe654bc.PNG)

I can execute commands like `cd ..` but the management console is shifted.
I tried an older version of ozwsh (where you have to start the manager via a shell script) and there is no message like this.

Can somebody reproduce the error or has some hints to fix the problem? Thanks in advance!

my system:
OS: Linux Mint 17 32 Bit `3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014 i686 i686 i686 GNU/Linux`
python-openzwave commit: b4476e27c9
Python: `Python 2.7.6 (default, Mar 22 2014, 22:59:38)  [GCC 4.8.2]`
cython -V: `Cython version 0.20.1post0`

**Comment by bibi21000** [comment]
> Can somebody reproduce the error or has some hints to fix the problem? Thanks in advance!

Everybody should. 
It's due to the security update in oenzwave last month.
Should be fixed now, at least for the add_device and remove_device commands.
Could you please close this issue it the previous push fix it.
TIA

**Comment by m0rphi** [comment]
works like a charm! Thx ;)
