### ISSUE TITLE
'make tests' causing 18 errors

### ISSUE THREAD

**Issue by sidhuy** [OpenZWave/python-openzwave#61]
I am using Ubuntu and followed the installation steps here: https://github.com/OpenZWave/python-openzwave/blob/master/INSTALL_REPO.rst

It all worked fine until I got to 'make tests', it caused 18 errors many of them similar to ERROR: test_100_controller_name_FILENAME   See attached photos too.  Any help is much appreciated.
![make tests 1](https://cloud.githubusercontent.com/assets/12804842/21510447/810c8f86-cc61-11e6-8323-5a747330ffb6.jpg)
![make tests 2](https://cloud.githubusercontent.com/assets/12804842/21510446/810a004a-cc61-11e6-88ca-c1a188044eb8.jpg)

**Comment by bibi21000** [comment]
Duplicate #62
