### ISSUE TITLE
Build the app in Windows

### ISSUE THREAD

**Issue by killercode** [OpenZWave/python-openzwave#7]
Hi

I was trying to build the lib and api on windows but I'm struggling a lot because it says "error: Don't know how to compile src-lib/libopenzwave/libopenzwave.pyx"

I already installed cython with pip... does anyone knows how to workaround this?

I am willing to contribute with the windows setup :)

**Comment by killercode** [comment]
Ok found one of the issues:

on the setup-lib.py:
if os_name == 'win32':

if we are using windows 10 ( as an example) it doesn't work... we need to update it to:
if os_name == 'win32' or os_name=='nt':

Now when i am cythoning the openzwavelib it throws another error that i can't solve:

src-lib/libopenzwave/libopenzwave.cpp(356) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

**Comment by bibi21000** [comment]
Hi

> Cannot open include file: 'stdint.h': No such file or directory

This file is packaged with the libc in Linux.

But don't know where to find it on windows plateforms

**Comment by ZvikaZ** [comment]
What's the status of this?
Can we build it in Windows?
What are the instructions?
