### ISSUE TITLE
0.4.0.x Installation reports

### ISSUE THREAD

**Issue by bibi21000** [OpenZWave/python-openzwave#73]
If you successfully install and launch checks on your system, please add a comment with the following informations. It will help us if we break a specific machine/version in the future : 
OS (name, version, arch) :
Python version (full version): 
Python openzwave version : 
Python openzwave flavor (--git, --embed, ...) : 

If you fail, please open a specific issue

**Comment by eperdeme** [comment]
Worked for me:
OS (name, version, arch) :  jessie / Docker: resin/raspberrypi3-python:3.5
Python version (full version): Python 3.5.2
Python openzwave version : 0.4.0.26 
Python openzwave flavor: embed

**Comment by hoopty** [comment]
Created #74 for this.

FreeBSD, needs tweaking:
```
Python 3.5.3 (default, Apr 15 2017, 08:03:17) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print (sys.platform);
freebsd11
```

Here's the error:
```
Collecting python_openzwave
  Downloading python_openzwave-0.4.0.29.zip (133kB)
    100% |################################| 143kB 4.6MB/s 
    Complete output from command python setup.py egg_info:
    ImportError in : from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    NameError in : class bdist_wheel(_bdist_wheel) - Use bdist_egg instead
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9mb46u89/python-openzwave/setup.py", line 43, in <module>
        print(current_template.ctx)
      File "/tmp/pip-build-9mb46u89/python-openzwave/pyozw_setup.py", line 196, in ctx
        self._ctx = self.get_context()
      File "/tmp/pip-build-9mb46u89/python-openzwave/pyozw_setup.py", line 673, in get_context
        ctx = system_context(ctx, openzwave=self.openzwave, static=True)
      File "/tmp/pip-build-9mb46u89/python-openzwave/pyozw_setup.py", line 178, in system_context
        raise RuntimeError("Can't detect plateform")
    RuntimeError: Can't detect plateform
    <pyozw_setup.EmbedTemplate object at 0x8061596a0>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9mb46u89/python-openzwave/
```

**Comment by hoopty** [comment]
FreeBSD is fixed in 0.4.0.31, thanks!

**Comment by sylvaincherrier** [comment]
Hi,
on a Raspberry 3, with a RaZberry card : 
z-way-server works : i can configure and drive my devices through the website.

But running my app (written for python-openzwave 3.x) makes the z-way-server crashes : 
(log in /var/log/z-way-server.log are : 
RECEIVED UNKOWN PACKET TYPE: 0x00
....
Get Serial API Capablilites returned zero..
Notification: critical (z-wave): Cannot start Z-Wave binding: Error: Bad data - communication failed
)

the website running on 8083 says suddently "unable to load data" (instead of all the devices, and their values). My app seems to work, but nothing is sent or received from the devices (no communication)

OS (name, version, arch) : Raspbian(jessy) - 4.4.5 - armv7l 
Python version (full version): python 3.4.2
Python openzwave version : 0.4.0.31
Python openzwave flavor (--git, --embed, ...) : (installed with pip3)

I don't really know where to start. I think there is something that is different in the way to use the module from the previous version. Is there any documentation on how to upgrade ?
Thx a lot :-)
Cheers

UPDATE : 
Well, in facts, i was wrong, this is not the problem. Even with this error, the python module works (but the z-way-server crashes, that's true). My issue is this one : I have a Smart Switch AEOTEC Gen 5 (ref ZWO75). It is detected in z-way, i can switch it on and off. But in python-openzwave, this switch is not found in **get_switches()**.  I made a test with api_demo.py, and the device is seen, i get its COMMAND_CLASS, etc, but Retrieve switch section is empty.

**Comment by bibi21000** [comment]
@sylvaincherrier : 
There were no major updates in the python-openzwave library between 0.3 and 0.4. Most of the updates was in the setup process.
It seems that your problem comes from the openzwave c++ lib.
You can test the installation with pyozw_check -i -d /dev/xxxx. It may help you.
You can try the ozwdev flavor ... or fallback to an old version using the 0.3.x archives.
Hope this helps

**Comment by bibi21000** [comment]
Don't know if it"s related to your problem : https://github.com/OpenZWave/open-zwave/pull/1210

**Comment by sylvaincherrier** [comment]
Thx for your answers. 
I think i made mistakes : as i was checking my 0.3 version, i realise that z-way-server had crashed too. I think you can't run both z-way-server AND a program using the python-openzwave library, no ?
My problem was that my switch was not accessible with the get_switches() method (it was not the 0.4 version of the library that was guilty, but my new switch !)
My question is : how can i help you to make this switch being part of the result provided by the get_switches method ?
Cheers

**Comment by bibi21000** [comment]
What are the command_classes manage by your switch ?
Could you please cut and paste your comments from this issue in a new one ? 
As said in the first post, the goal of this ticket is to follow the build of python-openzwave on different plateform.
Thanks in advance

**Comment by fremag** [comment]
Hi,

I could install and run the shell and test Fibaro wall plug and motion sensor.

OS (name, version, arch) : Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
Python version (full version): Python 3.4.2
Python openzwave version : python-openzwave (0.4.0.31)
Python openzwave flavor (--git, --embed, ...) : embed


Thanks a lot for your work, it's way easier to install it now than previous versions

**Comment by Nico0084** [comment]
Worked for me:
OS (name, version, arch) : Ubuntu 16.04.2 LTS/ x86_64
Python version (full version): Python 2.7.12
Python openzwave version : 0.4.0.32
Python openzwave flavor: embed
 👍 1

**Comment by techgaun** [comment]
Has been working well for me:

OS (name, version, arch) : Ubuntu 16.04.2 LTS/ x86_64
Python version (full version): Python 3.5.2
Python openzwave version : 0.4.0.34
Python openzwave flavor: git
Using Aeon Labs Z-Stick

OS (name, version, arch) : Raspbian 8.0 ARMv7
Python version (full version): Python 3.4.2
Python openzwave version : 0.4.0.34
Python openzwave flavor: git
Using Razberry

**Comment by sylvaincherrier** [comment]
Ok for me too

OS : Raspbian jessie
Python: 3.4.2
python-openzwave : 0.4.0.35

Thx for your work :-)

**Comment by chilicheech** [comment]
I'm trying to install it in an ubuntu docker container on my rpi2. I'm getting this error:
```
root@2e0c2065789a:/# pip3 install python_openzwave --install-option="--flavor=ozwdev"
/usr/lib/python3/dist-packages/pip/commands/install.py:212: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting python_openzwave
  Using cached python_openzwave-0.4.0.35.zip
Collecting PyDispatcher>=2.0.5 (from python_openzwave)
  Using cached PyDispatcher-2.0.5.tar.gz
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from python_openzwave)
Skipping bdist_wheel for python-openzwave, due to binaries being disabled for it.
Skipping bdist_wheel for PyDispatcher, due to binaries being disabled for it.
Installing collected packages: PyDispatcher, python-openzwave
  Running setup.py install for PyDispatcher ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f638a3zc/PyDispatcher/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7qalqf18-record/install-record.txt --single-version-externally-managed --compile --flavor=ozwdev:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --flavor not recognized

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f638a3zc/PyDispatcher/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7qalqf18-record/install-record.txt --single-version-externally-managed --compile --flavor=ozwdev" failed with error code 1 in /tmp/pip-build-f638a3zc/PyDispatcher/
root@2e0c2065789a:/#
```
Any suggestions?

---
Update:
OK, so, lesson learned. Install all dependencies first, then install python_openzwave with the --flavor option.

---
OS : Ubuntu 17.04 Zesty ARMv7
Python: 3.5.3
python-openzwave : 0.4.0.35

**Comment by bibi21000** [comment]
Thanks for your help

**Comment by dshanske** [comment]
Anyone have any ideas how to resolve this? lib/python3.6/site-packages/libopenzwave.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

**Comment by dan-cristian** [comment]
works on raspberry pi 2 with z-wave usb stick, but have not tested to see if other nodes are visible
Linux pix 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

Define options for device /dev/ttyACM0
Start network
-------------------------------------------------------------------------------
Network is awaked. Talk to controller.
Get python_openzwave version : 0.4.7
Get python_openzwave config version : Git 2018-02-15 00:27
Get python_openzwave flavor : embed
Get openzwave version : 1.4.3102
Get config path : /home/haiot/PYC/venv/local/lib/python2.7/site-packages/python_openzwave/ozw_config
Controller capabilities : set(['primaryController', 'staticUpdateController'])
Controller node capabilities : set(['primaryController', 'beaming', 'routing', 'listening', 'staticUpdateController'])
Nodes in network : 1
-------------------------------------------------------------------------------
Wait for network ready (120s)
-------------------------------------------------------------------------------
Network is ready. Get nodes
------------------------------------------------------------
1 - Name :  ( Location :  )
 1 - Ready : True / Awake : True / Failed : False
 1 - Manufacturer : Z-Wave.Me  ( id : 0x0115 )
 1 - Product : ZME_UZB1 USB Stick ( id  : 0x0001 / type : 0x0400 / Version : 4)
 1 - Command classes : set(['COMMAND_CLASS_NO_OPERATION', 'COMMAND_CLASS_BASIC'])
 1 - Capabilities : set(['primaryController', 'beaming', 'routing', 'listening', 'staticUpdateController'])
 1 - Neighbors : set([]) / Power level : None
 1 - Is sleeping : False / Can wake-up : False / Battery level : None
------------------------------------------------------------
Driver statistics : {'retries': 0L, 'readCnt': 9L, 'readAborts': 0L, 'routedbusy': 0L, 'ACKCnt': 10L, 'OOFCnt': 0L, 'noack': 0L, 'broadcastWriteCnt': 9L, 'callbacks': 0L, 'writeCnt': 10L, 'badChecksum': 0L, 'nondelivery': 0L, 'CANCnt': 0L, 'NAKCnt': 0L, 'netbusy': 0L, 'SOFCnt': 9L, 'broadcastReadCnt': 0L, 'badroutes': 0L, 'ACKWaiting': 0L, 'dropped': 0L}
------------------------------------------------------------
`

**Comment by nwilging** [comment]
OS (name, version, arch): Windows 10 Pro 64 Bit
Python version (full version): 3.7.2
Python openzwave version : 0.4.19
Python openzwave flavor (--git, --embed, ...): default

Install the Silabs CP210x universal driver, then use the COM port as your device (e.g. `device = "COM3"`)

Setup was flawless, nice work guys.

**Comment by timmattison** [comment]
OS (uname -a output): Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
Python version: 3.7.3
Python openzwave version: 0.4.19
Python openzwave flavor (--git, --embed, ...): default

Works with [Aeotec Z-Stick Gen5](https://aeotec.com/z-wave-usb-stick/). My install commands:

```
sudo apt install -y make libudev-dev g++ libyaml-dev
python3 -m venv python_openzwave
cd python_openzwave
source bin/activate
python3 -m pip install python_openzwave
pyozw_check
pyozw_check -i -d /dev/ttyACM0
```

**Comment by kklopfenstein** [comment]
OS (name, version, arch) : Linux 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
Python version (full version): 3.5.3
Python openzwave version : 0.4.19
Python openzwave flavor (--git, --embed, ...) :default

Works with HomeSeer SmartStick +

Installation initially failed. I had to install python3-dev to resolve.

**Comment by JanTalens01** [comment]
OS: Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
Python Version: 3.7.3
Python OpenZwave version: 0.4.19

Using "pip install python_openzwave" failed with error "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oAEqGr/Louie/".

Instead used "pip install 'PyDispatcher>=2.0.5'" and "pip install python_openzwave  --no-deps --install-option="--flavor=git"".
Checked the installation with "pyozw_check", but this command returned "command not found"

Anybody a suggestion how to resolve this problem?

**Comment by PeteCal** [comment]
Tried this for my RPi:
https://openzwave.github.io/python-openzwave/README.html

More problems then I can mention.
I get the feeling time has past openZwave by.  But I need a replacement.  I tried a few things including zwavejs2mqtt.  I can't get anything to work.

If anyone crosses this thread, please give me some alternatives.
