### ISSUE TITLE
pyozwweb error (on Python 3.5.3)

### ISSUE THREAD

**Issue by hoopty** [OpenZWave/python-openzwave#77]
Is pyozwweb not Python 3 compatible?  If not, please advise on the best way to use it in conjunction with my python-openzwave in a Python3 venv.  Thanks!

```
$python3 run.py 
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    from pyozwweb.app import create_app, run_app
  File "/home/hass/hass/lib/python3.5/site-packages/pyozwman-0.4.0.31-py3.5.egg/pyozwweb/app/__init__.py", line 53, in <module>
    from louie import dispatcher, All
ImportError: No module named 'louie'
```

**Comment by bibi21000** [comment]
pyozwweb is an example. It was developped because many people was asking "how can we use python-openzwave in a webapp"
It has many bugs and was not converted to be python 3 compliant. 
As far as I remember there was a memory leak with the gevent-socketio.

**Comment by hoopty** [comment]
Sounds like ozwcp :(
What is the best way to perform diagnostics and configuration with the zwave network and nodes?   Need to rename/configure nodes that Home Assistant interacts with and would prefer to use the same python library it uses if possible.

**Comment by bibi21000** [comment]
>What is the best way to perform diagnostics and configuration with the zwave network and nodes?
Can't Home-assistant do this ? Everything is available in the API.
For name changing, you can edit your zwcfgXXXX.xml by hand as long as you respect the xml syntax.
You can also use a virtual env with python2
And finally, you can use openzwave-control-panel

**Comment by turbokongen** [comment]
@hoopty all the things you need is available in homeassistant.  Look in the services page under zwave services. Soon all those will be available in a UI inside. I just need some time to get everything sorted properly.

**Comment by bibi21000** [comment]
@turbokongen : i've merge all update sfrom python3 branch in master. and remove it.
You should update your documentation

**Comment by turbokongen** [comment]
@bibi21000 Thank you for that info. Very useful. We have updated our docs now.

**Comment by hoopty** [comment]
Thanks!  I'm using the services in HA, and looks to be working.

**Comment by ThomasCr** [comment]
any way to get this fixed?
