### ISSUE TITLE
ZwaveOption don't see user_path

### ISSUE THREAD

**Issue by dignac3** [OpenZWave/python-openzwave#87]
Hello guys,

I'm doing a project where i need to use this librarie in order to control 1 or multiple switch. After installing python Openzwave and Open Zwave, i tried to launch apidemo.py and helloWorld.py but each time, I get the same error :
`Traceback (most recent call last):
File "zwave.py", line 85, in <module>
network = ZWaveNetwork(options, autostart=False)
File "/usr/local/lib/python2.7/dist-packages/openzwave/network.py", line 326, in __init__
self.dbcon = lite.connect(os.path.join(self._options.user_path, 'pyozw.sqlite'), check_same_thread=False)
File "/usr/local/lib/python2.7/dist-packages/openzwave/option.py", line 339, in user_path
return self._user_path
AttributeError: 'ZWaveOption' object has no attribute '_user_path'
`
I trie many things like rename user_path into _user_path, or remove it but the problem persist and I don't know what to do.

NB: I got some issues to install openZwave python too so maybe all is not installed correctly

Thanks !

**Comment by bibi21000** [comment]
Hi
Should be fixed.
I revert this PR https://github.com/OpenZWave/python-openzwave/issues/87
