### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bibi21000** [OpenZWave/python-openzwave#93]
@techgaun
We could discuss here

**Comment by techgaun** [comment]
@bibi21000 sure thanks!

Since this repo already has sphinx setup, I think this would be fairly easy but I myself have not done it before. Looking at https://docs.readthedocs.io/en/latest/getting_started.html and https://docs.readthedocs.io/en/latest/builds.html, I believe we can easily host the docs on readthedocs.

**Comment by bibi21000** [comment]
I'm ok with that. I've create an account and put a badge on the readme, 
See https://github.com/OpenZWave/python-openzwave/commit/df3eddeacac4672f3e7e36db6e3752428ce1a4d9
If I need to do some configuration in the readthedoc account, let me know
Thanks

**Comment by techgaun** [comment]
@bibi21000 thanks for the update. I see that its not working fine(the pages are there but autodoc is not working) and as it seems, the problem is most likely because of the lack of appropriate C header files thus not letting libopenzwave compile. The steps seem to pass but if you expand the build steps, there must be ImportError. It seems that they have [conda support](http://docs.readthedocs.io/en/latest/conda.html) but I saw some of the issues mentioning that conda support is not perfect.

**Comment by techgaun** [comment]
I was trying to see if I can get around with sys.path.insert (https://github.com/OpenZWave/python-openzwave/compare/master...techgaun:doc-updates?expand=1) and the documentation (I'm using this for test) consists of information for some of the modules eg. http://pyozw.readthedocs.io/en/latest/value.html but the problem of libopenzwave is not going to be fixed. It seems that the only way would be to get conda working

**Comment by techgaun** [comment]
Looking it little bit further, we would have to create a conda recipe for systemd/libudev but I have no experience of creating conda recipes (seems simple enough as you have to just write bash script and meta.yml file describing your recipe; I'll give it a try over the weekend). Trying to create systemd recipe might be little complex than others though.

The other option might be to use travis and have it push to github page automatically on every successful master branch build. In that case, our documentation could be available on python-openzwave.github.io

**Comment by bibi21000** [comment]
Hi
Sorry for the long delay, it's summer here so it's cool to be outside :) 
I'm using github.io on other personal projects on github, it's fine.
But we must find a way to "versioning" documentation; ie to find the right documentation of a specific version ie 0.4.1.
May be it should be a simple html page (or rst) populating when 'make new-version' ?
I think I will publish the 0.4.1 after adding it ?
Nothing to do with this ticket but what 'kind' of user are you : number of nodes, type of nodes, home-assistant ?
Do you use it every day ? What is your opinion about stability ? Do you "reboot" ?
I just want to have some feedback, there was 800 uniques clones on github in the last 15 days and only some bad reports :( ;)
One contributor propose to switch from cython to pybind. Actually, it seems not stable. 
So I don't know if it's a good idea to remove cython ;)
To be short every comment is welcome :)
Thanks for your job

**Comment by techgaun** [comment]
@bibi21000 its definitely awesome to be outside during summer. sure yeah versioning the documentation on github.io would be really cool. I really wish readthedocs worked for this but I could not get around libudev header files.

I am currently using python-openzwave for building a system with controller, 7-10 nodes in a network. I am not using home-assistant so I'm using python-openzwave for talking with zwave device through the cloud api. I also use devices that require security command class such as door locks.

I use it every day and I've not found any problem so far. It feels quite stable to me. I don't usually reboot for the purpose of re-initializing zwave network but for other purposes.

I looked at cython vs pybind as well but I didn't find any compelling reasons to switch but I didn't look in details either. I will try to contribute more and more in coming days so I hope to get your ideas and suggestions. Thanks for building this library :+1:

**Comment by bibi21000** [comment]
In the past, using cython was a pain ;) See #2
I don't test the pip installation process in this case, maybe it should work now.
So that's why I was thinking that should be a good idea. Because of the build speed too ( ie on a raspberry )
But my priority is stability :)
Thanks for your feedback

**Comment by techgaun** [comment]
I'm installing via pip (as well as from repo) bunch of times every day and its not been that bad for me. On RPi, its little slower but I am not so worried about it so far as there're several other things that are even slower on RPi. I agree with you that stability should be the first priority.
